### ISSUE TITLE
Documentation for how to write a driver

### ISSUE THREAD

**Issue by sirupsen** [datafold/data-diff#100]
We need a section of the README we can point people to. Many things are documented inline, but a starting point would be nice, e.g. cover:

* Threading
* How to support types (rounding)
* Writing tests (important)

**Comment by sirupsen** [comment]
As discussed with @erezsh, we'll work on this once some more refactoring has been done.

**Comment by erezsh** [comment]
Done - https://data-diff.readthedocs.io/en/latest/new-database-driver-guide.html
