### ISSUE TITLE
Let the differ choose a shared hashing algorithm

### ISSUE THREAD

**Issue by erezsh** [datafold/data-diff#103]
Right now we only support `md5` for hashing columns.

However, for some databases that might not be feasible. For example, in `mssql` it's too slow, and sounds like Spanner only supports sha1.

I think the solution should be to allow several implementations in subclasses of `Database`, and have the differ choose the best one that's shared between them. (or throw an error if there isn't one)

See issues #51 and #99.

**Comment by sirupsen** [comment]
Agree. sha1 is also sometimes faster than md5, because some instruction-sets have specific instructions for it, but not for md5. crc32 is also generally faster than both of those.

**Comment by abhinav1912** [comment]
I think this should be broken down into 2 tasks:
1. Adding a list of supported algorithms to the base/child classes, and refactor `md5_to_string` to something generic (maybe something like `hash_to_string`?)
2. Adding these changes to the interface/CLI where the DB type determines the intersection of hashing algorithms and offers a choice (and/or a default)

I'd be happy to start working on this, if it hasn't been picked up already.

**Comment by sirupsen** [comment]
@abhinav1912 it'd be awesome if you could pick this up!

If you can do some research for (1) about what kinds of "alternate" negotiations we can do, and how you'd implement it, that'd be a great start before you start implementing it 👀 For example, for MSSQL, how can we do strings if we can't do md5 fast?

**Comment by abhinav1912** [comment]
@sirupsen good point, I'll start looking into the alternatives and probably create a table of algorithms for each database. Will reach out on the Slack channel to clarify a few questions though.
As for MSSQL, [here's](http://kejser.org/exploring-hash-functions-in-sql-server/) a good article highlighting the performance of each hashing algorithm. `CHECKSUM` has good perfomance but poor hashing, `MD/SHA` algorithms have worse performance but better hashing. Doing better than `MD5` does seem a little difficult imo.

**Comment by sirupsen** [comment]
That MD5 performance doesn't look that bad... I wonder why it came up so slow in our tests. Maybe the instance just didn't have enough CPU? Might be worth confirming that result first!

**Comment by abhinav1912** [comment]
The performance point raises another question: is there be some script/utility that can calculate perf metrics for the current build? If not, then this could be a good addition.
