### ISSUE TITLE
Add support for Teradata

### ISSUE THREAD

**Issue by aribosa** [datafold/data-diff#105]
Hello guys! 

First of all, let me thank you for this incredible package you've achieved. I find myself with this recurrent problem of trying to compare two "mirror tables" or tables that are being migrated.

I was going to ask you if you've considered including Teradata to the supported engines.
Do you need help with it? I'm not a professional coder, but it would be great to contribute in this project.

Greetings from Argentina!

**Comment by aribosa** [comment]
Thank you @glebmezh for your tough work.

I would love to make my first contribution to an open source project, so I'll fork the main branch to build a Teradata adapter!

**Comment by mateocolina** [comment]
Hi @aribosa did you advance in the topic? We would also be interested in using it, or build it ourselves.
