### ISSUE TITLE
CSV support

### ISSUE THREAD

**Issue by Vponed** [datafold/data-diff#107]

**Comment by sirupsen** [comment]
Not yet, but it's definitely doable. We'll track that here!

**Comment by glebmezh** [comment]
@Vponed thanks for proposing this. It would be super helpful if you could describe the use case for diffing CSVs and how does this fit into the workflow?

**Comment by Vponed** [comment]
> 

I have no idea)
But your code (which I have never even used) clearly does just that with databases - it fragmentes and compares in stages... A database (with which I have never worked in its pure form)) is fields and data. CSV is also fields and data. And even a text file can be perceived like that - one field, data (lines) different. You just need a different approach to parsing?

**Comment by rupurt** [comment]
Would definitely love this. Our use case would be mainframe record files and CSV exports of databases not on the supported list e.g. Db2 (most databases can export to CSV)
