### ISSUE TITLE
How soon you will support Microsoft SQL Server & Azure SQL Server???

### ISSUE THREAD

**Issue by JDface** [datafold/data-diff#108]

**Comment by sirupsen** [comment]
Hey @JDface, it's certainly high on the priority list, you can see https://github.com/datafold/data-diff/issues/51 for more information on why it's not supported yet! I'm closing as it's a dup of that.

What column types do you need in particular?

**Comment by JDface** [comment]
From MSSQL standpoints, database tables have all types of data types binary, varchar, image, text,
