### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by abhinav1912** [datafold/data-diff#129]
Most repositories contain either:
1. A _Contributing_ section in the `README`, or
2. A `Contributing.md` file

It would be beneficial to have one here as well.

**Comment by nolar** [comment]
I would slightly extend it — it would be good to fit into GitHub's vision of a well-defined repo by reaching all Community Standards here: https://github.com/datafold/data-diff/community.

**Comment by erezsh** [comment]
I feel this is done. Feel free to re-open or make suggestions.
