### ISSUE TITLE
Support Browser-based SSO in Snowflake connector

### ISSUE THREAD

**Issue by franloza** [datafold/data-diff#130]
It would be great to support [Browser-based SSO](https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#browser-based-sso) to connect to Snowflake.

When federated authentication is enabled for an account, Snowflake does not recommend maintaining user passwords in Snowflake so using SSO is the only way to connect and authenticate with a Snowflake client.

Currently, if I try to connect with an external authenticator, I get the following error:
```
data-diff \
    "snowflake://<user>@<account>/<database>/<schema>?warehouse=<warehouse>&role=<role>&authenticator='externalbrowser'" \
    <table> \
    "snowflake://<user>@<account>/<database>/<schema>?warehouse=<warehouse>&role=<role>&authenticator='externalbrowser'" \
    <table>
```

```
snowflake.connector.errors.ProgrammingError: 251006: Password is empty
```

In other tools like dbt, this feature is supported by providing the `authenticator` option: https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile#sso-authentication

**Comment by sirupsen** [comment]
@franloza this is definitely legit. Is this something you'd be wiling to contribute?

**Comment by franloza** [comment]
@sirupsen Sure! This seems a pretty good first issue.

**Comment by franloza** [comment]
@sirupsen I don't think it's necessary to open a PR, the current implementation supports the use of an external browser to authenticate. The problem was that my connection string was wrong 🤦 

I was using the following URI:
```
"snowflake://<user>@<account>/<database>/<schema>?warehouse=<warehouse>&role=<role>&authenticator='externalbrowser'"
```

I used quotes to pass `externalbrowser` parameter because I followed the Snowflake documentation for the [Python client](https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#setting-up-browser-based-sso): 

Client | Instructions
-- | --
Python | Pass authenticator='externalbrowser' to the snowflake.connector.connect() function.

However, the correct instructions are the one for JDBC client:

Client | Instructions
-- | --
JDBC | Set authenticator=externalbrowser in the connection string for the driver.

With the following URI, the connection works:
```
"snowflake://<user>@<account>/<database>/<schema>?warehouse=<warehouse>&role=<role>&authenticator=externalbrowser"
```

Is there any place where do you think this should be documented or should I close the issue?

**Comment by sirupsen** [comment]
OH very cool, we definitely need that documented! My best suggestion right now is to add a comment or footnote to the Snowflake connection string in the database table (try and see what looks less invasive and put it up for review) describing how to do this.

What does the workflow look like when you pass that? Does the driver hook-in and do an OAUTH workflow with stdin?
