### ISSUE TITLE
Oracle, BigQuery, Redshift on CI

### ISSUE THREAD

**Issue by sirupsen** [datafold/data-diff#138]
Currently we test those locally since they run in the Cloud and in Oracle & Redshift's case require a bastion host to be accessible from our local machines. BigQuery also has its own config. We'd love to get those running in CI (https://github.com/datafold/data-diff/pull/135). We have Snowflake, MySQL, Presto, and Postgres as of https://github.com/datafold/data-diff/pull/135

@cfernhout you able to take this on? ❤️

**Comment by erezsh** [comment]
Duplicated of #112
