### ISSUE TITLE
Remove Preql scripts; rely on database_types.py instead

### ISSUE THREAD

**Issue by sirupsen** [datafold/data-diff#139]
@erezsh wdyt about removing all the Preql scripts and just rely on `database_types.py` instead? We can add instructions on running a single test to seed your local database if you want to just run it locally.

I think this would cut down on the amount of testing code we have to maintain

**Comment by erezsh** [comment]
If someone wants to send a PR for it, they're welcome to.

**Comment by erezsh** [comment]
Things that it would have to solve:

- DDL operations (mostly create & drop, but requires translating column types)
- Resolving table names, so it uses the right schema, handling of lower/upper-case mangling, and avoiding reserved keywords (like `comment` in oracle)
- (to be updated)

So far, trying to get our tests to run on all databases, only makes me think that more of them should use Preql, not less.

**Comment by nklsw** [comment]
I just stumbled across this while building a driver for Exasol. Is there anything new on this topic? How should one currently deal with testing new drivers for databases that are not supported by Preql?

**Comment by erezsh** [comment]
@nklsw Preql is not necessary to test new drivers. Read this guide: https://data-diff.readthedocs.io/en/latest/new-database-driver-guide.html

**Comment by nklsw** [comment]
@erezsh Do I understand you correctly that I should not include a new database in [TEST_DATABASES](https://github.com/datafold/data-diff/blob/7824b0b50edcde2dc19726708078b1d9fe623662/tests/test_diff_tables.py#L26)? Just out of interest: What are these tests for and why should not all supported databases be tested there?

**Comment by erezsh** [comment]
Task completed.
