### ISSUE TITLE
snowflake.connector.errors.ForbiddenError: 250001 (08001): Failed to connect to DB. 

### ISSUE THREAD

**Issue by schottma** [datafold/data-diff#141]
I keep getting the following error:

`snowflake.connector.errors.ForbiddenError: 250001 (08001): Failed to connect to DB. Verify the account name is correct: fi45185.snowflakecomputing.com:443. HTTP 403: Forbidden`

I've ran this with Poetry and printed out the credentials I was passing in and they all look correct. I've tried signing in with multiple different users and passwords and I am still getting the same error. I can't figure out what is going wrong. My account is fi45185.east-us-2.azure.snowflakecomputing.com- I am only inputting fi45185 as the account.

**Comment by nolar** [comment]
Hello. Thanks for asking!

According to Snowflake's documentation, you have to specify the full account id unless it is in AWS & the US West (Oregon) region — the only one that can be skipped.

* https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#using-an-account-locator-as-an-identifier
* https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#non-vps-account-locator-formats-by-cloud-platform-and-region

I see that your account mentions "azure", so the id should be `fi45185.east-us-2.azure` — this logic applies to all Snowflake tools.

Can you please try it and tell us how it goes?

**Comment by nolar** [comment]
I hope my answer did help, so I am closing the issue. If not, feel free to reopen.
