### ISSUE TITLE
How to pass credential file while connecting to bigquery database

### ISSUE THREAD

**Issue by jitendra-bansal** [datafold/data-diff#156]
Hi Team,
I am confuse to use data-diff for bigquery database as it is mentioned | BigQuery      | `bigquery://<project>/<dataset>`

how to pass credential file using this?

It will be helpful if any example is added in readme to use bigquery

**Comment by jitendra-bansal** [comment]
OK I will check with a configuration file.
But I am using data-diff module into my python codebase. So, how to pass this credentials using python.

like the example they have given
import logging
logging.basicConfig(level=logging.INFO)

from data_diff import connect_to_table, diff_tables

table1 = connect_to_table("postgresql:///", "table_name", "id")
table2 = connect_to_table("mysql:///", "table_name", "id")

for different_row in diff_tables(table1, table2):
    plus_or_minus, columns = different_row
    print(plus_or_minus, columns)

**Comment by erezsh** [comment]
@jitendra-bansal I created a PR for this change. You can install it with:

```
pip install git+https://github.com/datafold/data-diff.git@refs/pull/157/head
```

You would then connect using something like this:

```python
db1 = dict( driver = "bigquery", credentials = "..." )
table1 = connect_to_table(db1, "table_name", "id")
```

**Comment by jitendra-bansal** [comment]
Hi @erezsh  thanks for the help this PR 157 worked for me.
