### ISSUE TITLE
key_column is overrided to be using id

### ISSUE THREAD

**Issue by imfaridz** [datafold/data-diff#169]
Hi,

I am currently trying to use data_diff module in python programmatically as stated in the README.md, somehow I encountered this issue that even though i already stated the key_column to be using column that i declare when calling the function, it force me to use id as key_column.

Here's the TableSegment output after i declare use the connect_to_table function:
`TableSegment(database=<data_diff.databases.postgresql.PostgreSQL object at 0x1079f4c70>, table_path=('table_name',), key_column='date_key', update_column=None, extra_columns=(), min_key=None, max_key=None, min_update=None, max_update=None, case_sensitive=True, _schema=None)`

but when I use the diff_tables function it throws error as such:
`ValueError: Column 'id' not found in schema for table TableSegment(database=<data_diff.databases.postgresql.PostgreSQL object at 0x1079f4c70>, table_path=('table_name',), key_column='id', update_column=None, extra_columns=(), min_key=None, max_key=None, min_update=None, max_update=None, case_sensitive=True, _schema={})`

Ideally, the key_column should be align with the TableSegment I passed to the function right ?
the version that i used is `Version: 0.2.3`

Thanks!

**Comment by erezsh** [comment]
Hi,

Yes, calling `diff_tables()` currently overrides these attributes of TableSegment, which is a mistake. We'll fix it soon.

Meanwhile, you can just use `TableDiffer().diff_tables(a, b)` directly, which should bypass this bug.

**Comment by imfaridz** [comment]
Got it @erezsh , it works now. 
thanks for the answer
