### ISSUE TITLE
Error when connecting to BigQuery (UX)

### ISSUE THREAD

**Issue by lihan** [datafold/data-diff#188]
```
data_diff.databases.base.ConnectError: Exception when trying to execute SQL code:
    SELECT column_name, data_type, 6 as datetime_precision, 38 as numeric_precision, 9 as numeric_scale FROM my_table_name.INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'booking' AND table_schema = 'my_table_name'
```

Got error: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/{project-id}/jobs?prettyPrint=false: ProjectId and DatasetId must be non-empty

**Comment by erezsh** [comment]
What are you using for the URI? It should be something like

```
bigquery://my-project-id/my-dataset-id
```

**Comment by lihan** [comment]
@erezsh Yes, I were follow that format. my project id contains '-', not sure if that makes a difference.
`bigquery://my-project-id/dataset`

**Comment by erezsh** [comment]
Can you please include more information? How are you running data-diff, and what's the full output + error traceback?

It would be useful if you can run data-diff with `-d` for debug.

**Comment by erezsh** [comment]
Closed due to inactivity.
