### ISSUE TITLE
Not able to use the extra columns parameter

### ISSUE THREAD

**Issue by akulgoel96** [datafold/data-diff#191]
I am running the current master version of data-diff. However when I run the below command, I am getting an error regarding the `columns` parameter not getting recognized.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/13823055/182597232-56ea07dc-62f7-4836-9c91-fcdccd400398.png">

**Comment by erezsh** [comment]
Are you using the latest version? (0.2.4)

Can you please paste this command as text?

**Comment by akulgoel96** [comment]
I am using the current master which is unreleased since it has the non-integer ID changes merged in this PR: https://github.com/datafold/data-diff/pull/179. 
Command: 
```data-diff presto://akul.goel@razorpay.com@trino-dev-coordinator-service.trino-dev.svc.cluster.local:8080/hive/sqoop_api sqoop_api.merchants presto://akul.goel@razorpay.com@trino-dev-coordinator-service.trino-dev.svc.cluster.local:8080/hive/realtime_hudi_api realtime_hudi_api.merchants -k id -v --json --bisection-factor 6 --bisection-threshold 100000000 –c name --min-age=2days -t created_date

**Comment by erezsh** [comment]
Try to copy+paste this command -

```
data-diff presto://akul.goel@razorpay.com@trino-dev-coordinator-service.trino-dev.svc.cluster.local:8080/hive/sqoop_api sqoop_api.merchants presto://akul.goel@razorpay.com@trino-dev-coordinator-service.trino-dev.svc.cluster.local:8080/hive/realtime_hudi_api realtime_hudi_api.merchants -k id -v --json --bisection-factor 6 --bisection-threshold 100000000 -c name --min-age=2days -t created_date
```

**Comment by akulgoel96** [comment]
Interesting, this worked. I diffed both the commands  and apparently that hyphen is some other unicode character and is causing the issue?

**Comment by erezsh** [comment]
Yes, that's my guess. (didn't check if it's the hyphen or around it, but same idea)

**Comment by akulgoel96** [comment]
Thanks for the prompt help! One final question: how do I pass multiple columns to this parameter? I tried giving it as as a comma separated string but didn't work. Also didn't find any sample values in the github documentation

**Comment by erezsh** [comment]
Happy to help!

Yes, I think this needs to be better documented.

You can pass `-c` several times, like `-c name -c another`.

**Comment by akulgoel96** [comment]
Thank you!
