### ISSUE TITLE
Error when using --update_at because column has string schema

### ISSUE THREAD

**Issue by ayyoubmaulana** [datafold/data-diff#195]
**Is your feature request related to a problem? Please describe.**
I use data diff to diffing between BigQuery and MySQL, i want to use `--update_column` flag but my `updated_at` column in MySQL has `string` schema so the command throw error like this 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/53739205/183299106-30531664-99a4-47ae-90cd-55ba86a0e2f2.png">

**Describe the solution you'd like**
make feature to convert or cast `updated_at` column from text to date or timestamp

**Comment by erezsh** [comment]
Can you please include a few sample values from your updated_at column?

**Comment by ayyoubmaulana** [comment]
this is sample of `updated_at` column that has string schema
<img width="177" alt="image" src="https://user-images.githubusercontent.com/53739205/183322008-08e420a2-5abd-4a22-9ad5-7ce512c53d23.png">

**Comment by ayyoubmaul** [comment]
any update for this issue ?

**Comment by erezsh** [comment]
Sorry, no update yet.

**Comment by ayyoubmaulana** [comment]
@erezsh How to save data-diff output to json ?

**Comment by erezsh** [comment]
Use `--json`

**Comment by ayyoubmaulana** [comment]
@erezsh where is the output will save ?

**Comment by ayyoubmaulana** [comment]
can i use this command `--json '/home/user/dir/output.json'` ? @erezsh

**Comment by erezsh** [comment]
You can do `--json > /home/user/dir/output.json`
