### ISSUE TITLE
Add support to ClickHouse

### ISSUE THREAD

**Issue by Javier162380** [datafold/data-diff#204]
**Is your feature request related to a problem? Please describe.**
On my job, we rely heavily on Clickhouse. Data-diff will be a useful tool for us.

**Describe the solution you'd like**
A common adapter like the ones used for the supported databases

**Describe alternatives you've considered**

**Additional context**
I can contribute to this feature

**Comment by erezsh** [comment]
> I can contribute to this feature

That's excellent!

You can read this guide to help you out: https://data-diff.readthedocs.io/en/latest/new-database-driver-guide.html

Let us know if you have any questions, or need any help!

**Comment by glebmezh** [comment]
ClickHouse support underway: https://github.com/datafold/data-diff/pull/217

**Comment by erezsh** [comment]
Support added.
