### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [datafold/data-diff#220]
ello! I have successfully put this package on to Conda Forge, and I have extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/data-diff-feedstock

**Comment by erezsh** [comment]
Hi @thewchan !

Thanks for making the package. It's always great to have contributions from the community.

It looks like you can handle this one without us. And our package is pretty simple, in terms of setup, no binaries or docker files etc. (at least not as part of the default installation).

But thanks for the invitation! Who knows, we might want to contribute to your package in the future.

**Comment by thewchan** [comment]
Thanks! If this changed you know where to find us!
