### ISSUE TITLE
Compare columns in a struct or Records  - Issues in BigQuery

### ISSUE THREAD

**Issue by Maxime-Laine** [datafold/data-diff#233]
**Is your feature request related to a problem? Please describe.**
I am unable to compare columns in as Struct in bigquery

**Describe the solution you'd like**
It would be great to have the possibility of reading the columns inside a structure or records and if possible in a other version to read the columns inside a nested record

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feat
<img width="356" alt="Capture d’écran 2022-09-13 à 11 49 45" src="https://user-images.githubusercontent.com/112859232/189870714-0c21d470-b9cb-4875-a61a-ddd94969136d.png">
ure request here.

**Comment by erezsh** [comment]
Hello, thank you for opening this feature request.

We have not yet tested data-diff with records.

Can you please describe the current behavior? Are you getting an error message, or is the diff failing to return the correct results?

**Comment by Maxime-Laine** [comment]
Hello

**Comment by erezsh** [comment]
If I understand correctly, data-diff currently can diff whole records, and you would like the ability to only diff specific fields inside a record? i.e. diff a subset of a record, instead of everything inside it?

**Comment by erezsh** [comment]
Closed due to inactivity
