### ISSUE TITLE
Use database configs from --conf in place of the DB_URI args

### ISSUE THREAD

**Issue by johnson-jay-l** [datafold/data-diff#246]
**Is your feature request related to a problem? Please describe.**
I want to keep our database configs in a config file, and reference the database in the CLI command in place of the DB_URI args ```data-diff DB1_URI TABLE1_NAME DB2_URI TABLE2_NAME```

This would let us abstract away the complex database args that we need for SSL, while being able to pass in any two tables from any of our databases without having to specify all of the table pairs in the config file.

I tried a few things and looked through the docs but couldn't figure out a way to do this.  

**Describe the solution you'd like**
Given a toml config file:

```
[database.redshift_prod]
driver = "redshift"
host = "proxy.example.com"
port = "443"
user = "db_user"
password = "none"
database = "some_db"
sslmode = "verify-full"
sslrootcert = "cert.pem"
sslcert = "cert-prod-x509.pem"
sslkey = "first.last@example.com"

[database.redshift_stage]
driver = "redshift"
host = "proxy.example.com"
port = "443"
user = "db_user"
password = "none"
database = "some_db"
sslmode = "verify-full"
sslrootcert = "cert.pem"
sslcert = "cert-stage-x509.pem"
sslkey = "first.last@example.com"
```

I want to run something like this:
`data-diff --conf config.toml database.redshift_prod some_table_1 database.redshift_stage some_table_1 -k some_col`

**Describe alternatives you've considered**
Option 1. Add all combinations of tables in `[run.test_diff]` toml blocks and call via: `data-diff --conf config.toml --run test_diff -k id`

Option 2. add the db_uri strings to environment variables and call them during `data-diff` cli runs

**Additional context**
n/a

**Comment by erezsh** [comment]
Thanks for the idea!

Solved and merged to master.

**Comment by erezsh** [comment]
Hi @johnson-jay-l ,

It seems that you're not using the `master` version. Keep in mind that installing `master` using pip will not override the last release, since they are still marked as the same version. You'll have to uninstall the old release first. (Or wait for Monday, I'll probably do a new release then)

**Comment by johnson-jay-l** [comment]
I tried uninstalling then installing again from master and it worked.  Thanks again!

`pip install git+https://github.com/datafold/data-diff.git@master`
