### ISSUE TITLE
Add support for Netezza

### ISSUE THREAD

**Issue by cnolanminich** [datafold/data-diff#259]
Taking a quick glance at https://github.com/datafold/data-diff/tree/master/data_diff/databases it doesn't seem like this would be _too_ complicated (famous last words!).

One thing I noticed is that Netezza does not have an unbounded varchar type, so any `to_text()` would need to find the max varchar or supply a sensible default.

I will take a closer look and comment back here, but just wanted to leave a note and say how excited I am about this project!

**Comment by erezsh** [comment]
Hello! I'm not familiar with Netezza, but if it behaves similarly to one of our existing supported databases, then I agree it should be pretty easy to add!

We don't rely on unbounded text size, and while we don't have an official default at the moment (perhaps we should!), 1024 seems like it would be a reasonable choice.

**Comment by erezsh** [comment]
Not sure what you mean. Tests are by nature trial-and-error. You run them and see what breaks.

I can suggest going incrementally, meaning first get it to diff Nettezza <-> Netezza, and only after diff against other databases, where you'll have to deal with the subtleties of value normalization.
