### ISSUE TITLE
Column not found [Snowflake]

### ISSUE THREAD

**Issue by lassebenni** [datafold/data-diff#286]
Hi,

I am trying to diff two tables in Snowflake using data-diff version `0.3.0rc2`

```
data-diff \
"snowflake://<USER>:<PASS>@<ACCOUNT>/<DATABASE>/<SCHEMA>?warehouse=<WAREHOUSER>&role=ACCOUNTADMIN" \
DIM_CUSTOMERS \
  PR.DIM_CUSTOMERS \
  -k CUSTOMER_ID \
  -c LAST_NAME \
  -m test_results_%t \
  --materialize-all-rows \
  --table-write-limit 10000
```

But getting the error:
```
ValueError: Column 'LAST_NAME' not found in: <data_diff.databases.snowflake.Snowflake object at 0x10c4a73d0>/DIM_CUSTOMERS, <data_diff.databases.snowflake.Snowflake object at 0x10c4a73d0>/PR.DIM_CUSTOMERS
```

Eventhough the `LAST_NAME` customer does exist (in both tables). Same issue with other columns I try to specify. It only works without specifying any additional columns next to the key column.

Any thoughts?

**Comment by erezsh** [comment]
Can you share the schema of the table? (just the column involved should be fine)

**Comment by lassebenni** [comment]
Sure! This is the schema 

<img width="772" alt="image" src="https://user-images.githubusercontent.com/7990862/201701004-48be758f-a5f1-4afa-bced-1292e19c5cd4.png">

**Comment by lassebenni** [comment]
I can confirm it works! Thanks for the effort!
