### ISSUE TITLE
The "How to use" URLs specified in the README file are broken

### ISSUE THREAD

**Issue by daniel-leicht** [datafold/data-diff#289]
I really wanted to use data-diff in my very big and important project as it perfectly suited my needs as I could use it from shell or Python.

But then, when it seemed all the stars were aligned for me, I found out that the URLs of:

- How to use from the shell (or: command-line)
- How to use from Python

Are broken and lead to 404 page!

You can just imagine the trauma and shock I went through! 
My disappointment is immeasurable and my day is ruined.

**Comment by erezsh** [comment]
I'm very sorry you had to experience such a traumatic event.

Can you tell me in what page the links are broken?

**Comment by daniel-leicht** [comment]
The following screenshot was taken from the main page of the project (the README file): 
![image](https://user-images.githubusercontent.com/17382506/201524641-6c4a0957-13bb-4eaf-844e-b4fbe7b64244.png)

I hope this matter can be rectified ASAP as I can't continue my day like this.

**Comment by erezsh** [comment]
Dear sir / madam,

Thank you for letting us know, we have now fixed the links.

We apologize again for our gross incompetence, and the terrible affront this has caused you.
