### ISSUE TITLE
Problems when trying to connect to Databricks

### ISSUE THREAD

**Issue by RobertBemmann** [datafold/data-diff#301]
# Description of the bug
When trying to connect to a databricks table I get an Assertion error
![image](https://user-images.githubusercontent.com/8913482/202710044-942a1baf-0edf-4f5b-9d79-933b35bd8313.png)

# Code you used
```python
# Optional: Set logging to display the progress of the diff
import logging
logging.basicConfig(level=logging.INFO)

from data_diff import connect_to_table, diff_tables

catalog_user = dbutils.secrets.get("data-platform", "catalog-user")
catalog_password = dbutils.secrets.get("data-platform", "catalog-password")
host = "abc.rds.amazonaws.com"

http_path = "sql/protocolv1/..."
access_token = "MyToken"
server_hostname = "dbc-123456-123a.cloud.databricks.com" 

source_endpoint = f"postgresql://{catalog_user}:'{catalog_password}'@{host}:5432/catalog-management"
target_endpoint = f"databricks://{http_path}:{access_token}@{server_hostname}/default"
# databricks://<http_path>:<access_token>@<server_hostname>/<catalog>/<schema>

table1 = connect_to_table(catalog_endpoint, "tour", "id")
table2 = connect_to_table(target_endpoint, "catalog__tour", "id")

for different_row in diff_tables(table1, table2):
    plus_or_minus, columns = different_row
    print(plus_or_minus, columns)
```

# Describe the environment
* just ran in a databricks notebook, in a Python env (3.8.0 (default, Dec  9 2021, 17:53:27))
* data-diff (0.2.8)

# Improvements
* It would help to give examples for the connection string and where to find this info, such as [here](https://learn.microsoft.com/en-us/azure/databricks/integrations/jdbc-odbc-bi#get-server-hostname-port-http-path-and-jdbc-url)
* also I'm not sure if I did something wrong with building the connection string or if the issue is that the the dsnparse returns `username` and not `user` ([docs](https://github.com/Jaymon/dsnparse/blob/master/dsnparse.py#L117-L127))

**Comment by erezsh** [comment]
We expect the databricks URL to look like this:

```
databricks://:<access_token>@<server_name>/<http_path>
```

The documentation is wrong, sorry, we will fix it soon.
