### ISSUE TITLE
Support `clickhouse+native` and `clickhouse+http` connection methods

### ISSUE THREAD

**Issue by anatoly-scherbakov** [datafold/data-diff#316]
**Is your feature request related to a problem? Please describe.**

```shell
data-diff postgresql://postgres@postgres/postgres mytable clickhouse+native://default:foo@clickhouse:9000 anothertable
[17:02:27] ERROR - No support for multiple schemes
```

**Describe the solution you'd like**
User should be able to use the URL scheme to specify preferred connection method.

Version:

```shell
data-diff==0.2.8
```

**Comment by erezsh** [comment]
Agreed!

For reference, the SQLAlchemy extension supports it: https://github.com/xzkostyan/clickhouse-sqlalchemy
