### ISSUE TITLE
ERROR - 'database'

### ISSUE THREAD

**Issue by anatoly-scherbakov** [datafold/data-diff#317]
**Describe the bug**

```shell
data-diff postgresql://postgres@postgres/postgres x clickhouse://default:badoom@clickhouse:9000 y
[17:07:09] ERROR - 'database'
```

This error message no longer appears if we use the following form:

```shell
data-diff postgresql://postgres@postgres/postgres x clickhouse://default:badoom@clickhouse:9000/default y
```

We have now specified Clickhouse database name using `/default`.

There are two issues here:

* Error message is not informative; it does not indicate where the command is wrong
* The tool might substitute the default database name (which is `default` for Clickhouse).

**Describe the environment**

`data-diff` v0.2.8.

**Comment by erezsh** [comment]
Thanks for reporting! I agree the error message can be better.

Can you please point to the Clickhouse documentation where "default" is the default database?

**Comment by anatoly-scherbakov** [comment]
- Mentioned in section about [server settings](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#default-database),
- and also in the [tutorial](https://clickhouse.com/docs/ru/getting-started/tutorial/#create-tables).

**Comment by erezsh** [comment]
Fixed in `master`.
