### ISSUE TITLE
Cannot use data diff on unsorted data or data without primary key. 

### ISSUE THREAD

**Issue by paarijat7** [datafold/data-diff#332]
I am trying to find data difference between two dataset one in vertica and other in sql server . I neither have primary key nor sorted data. to tackle primary key issue, I am trying to make composite key and run query  according to it. It is throwing me raw schema. 

These are changes i tried to make:

1. 
![image](https://user-images.githubusercontent.com/111218528/205833657-7abe787d-d553-403c-afa3-558464bafd64.png)
2. added support of mssql
![image](https://user-images.githubusercontent.com/111218528/205834707-722d6cdc-9b67-4647-bd4a-4ede697c25f5.png)

Thank you.

**Comment by erezsh** [comment]
Hi, data-diff currently doesn't support composite keys for cross database diffing. See this issue: https://github.com/datafold/data-diff/issues/110

We hope to fix this issue soon.

Also, next time please include text rather than a screenshot, and if you're getting an error, include the traceback.

**Comment by paarijat7** [comment]
is there anyway  by which i can include composite key as functionality.  I am trying to make changes in both tablesegments.py and sql.py

**Comment by erezsh** [comment]
Please read the issue I linked. I detailed my plan to add a composite key (hint: It's not easy!)

**Comment by erezsh** [comment]
This issue has been fixed, and should be closed
