### ISSUE TITLE
`data-diff` internals expects `server_hostname` whilst the Databricks `DB_URI` expects `server_name`

### ISSUE THREAD

**Issue by JCZuurmond** [datafold/data-diff#349]
`data-diff` internals  expect [`server_hostname`](https://github.com/datafold/data-diff/blob/7abe5a5226cb0884f19146db71df4b4fb057dd0e/data_diff/sqeleton/databases/databricks.py#L107) whilst the Databricks [`DB_URI`](https://github.com/datafold/data-diff/blob/7abe5a5226cb0884f19146db71df4b4fb057dd0e/docs/supported-databases.md?plain=1#L12) expects `server_name`. This isn't very clear when translating the cli scan to a programmatic scan.

**Comment by erezsh** [comment]
Agreed. I'll change the URL to `server_hostname`.

**Comment by erezsh** [comment]
Fixed.
