### ISSUE TITLE
Add support for Hive

### ISSUE THREAD

**Issue by nmani1191** [datafold/data-diff#357]
data-diff looks exciting and I am looking forward to Hive support which will be handy during Datawarehouse migrations from Hive to Cloud.

**Comment by gualber98** [comment]
Same here, my company is migrating from Hive to Snowflake and would like to use Datafold.

**Comment by nmani1191** [comment]
I am looking on the possibilities of creating connector for hive.

**Comment by dlawin** [comment]
Hi @nmani1191, adding additional database connectors is not a priority for the project at this time. You could fork the project and add that support in a separate repo, but we're not in a position currently to be able to accept the additional overhead.
