### ISSUE TITLE
Databricks: support column of type `Text()` as key

### ISSUE THREAD

**Issue by JCZuurmond** [datafold/data-diff#358]
**Is your feature request related to a problem? Please describe.**

We have tables that contain key columns with the type `Text()`. We can not change these columns; we have to use the tables as is.

**Describe the solution you'd like**

I want to use columns with the type `Text()` as the key.

**Describe alternatives you've considered**

None. If this feature will/can not be supported, then I will see if can create views that convert the key columns to numeric columns.

**Additional context**

Running on Databricks

**Comment by JCZuurmond** [comment]
👆

**Comment by dlawin** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> We have tables that contain key columns with the type `Text()`. We can not change these columns; we have to use the tables as is.
> 
> **Describe the solution you'd like**
> 
> I want to use columns with the type `Text()` as the key.
> 
> **Describe alternatives you've considered**
> 
> None. If this feature will/can not be supported, then I will see if can create views that convert the key columns to numeric columns.
> 
> **Additional context**
> 
> Running on Databricks

Thanks for reporting this @JCZuurmond, we're not currently working on this but may in the future, in the meantime we'd happily accept a community contribution

**Comment by leoebfolsom** [comment]
A similar issue has cropped up related to Databricks `Date` PKs:

```
ERROR - Cannot use a column of type UnknownColType(text='DATE') as a key
```

**Comment by JCZuurmond** [comment]
👆

**Comment by ism21** [comment]
Running into the same issue.

**Comment by ferdyh** [comment]
Yes, same issue here... All columns we use have surrogate keys which are strings.

**Comment by dlawin** [comment]
See context from #539 

https://github.com/datafold/data-diff/issues/539#issuecomment-1773354733

**Comment by ferdyh** [comment]
@dlawin Okay, I can understand the reasoning as to why. The primary key I use is an md5 (aphanumeric) generated from a string. How would I force data-diff to see this as an ArithString? That should be a workable solution if i'm understanding this correcty?

**Comment by glebmezh** [comment]
Hi all - 

I'm sorry for the delay in following up on this. @JCZuurmond, thank you for taking the time to raise this issue!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support.

If that's of interest, over the past few months, we have rewritten the diffing engine in Datafold Cloud and solved many issues that existed in this package.

-Gleb
