### ISSUE TITLE
Receive `It cannot be used as a key.` warning for column specified in `extra_columns`

### ISSUE THREAD

**Issue by JCZuurmond** [datafold/data-diff#360]
**Describe the bug**

I receive the following message about a column specified in the `extra_columns`:

```
WARNING:database:Mixed Alphanum/Non-Alphanum values detected in column <column identifier>. It cannot be used as a key.
```

I find the warning confusing since the column is an `extra_columns` and not a `key_columns`

**Describe the environment**

- Python 3.9.13
- data-diff==0.3.1

**Comment by erezsh** [comment]
Hi @JCZuurmond , I understand the confusion. We'll improve the warning. Anyway, if you're not using it as a key, you can ignore the warning.

**Comment by JCZuurmond** [comment]
👆

**Comment by dlawin** [comment]
> 👆

@JCZuurmond are you able to reproduce this on a more recent version? I believe this has been fixed, but it seems the PR was not linked

**Comment by JCZuurmond** [comment]
Hi @dlawin , unfortunately I can not verify this easily. Let's close the issue for now
