### ISSUE TITLE
Missing Data's type In data-diff

### ISSUE THREAD

**Issue by titou41** [datafold/data-diff#361]
**Describe the bug**
We are using Datafold (and data-diff) to compare two database : one mysql and one postgresql.
In both database, we are missing some data type.
Here is the missing type :

Mysql :
- text
- tinyint
- smallint
- mediumtext
- date
- point
- longtext
- tinytext
- json

Postgresql :
- date
- geometry

Describe which OS you're using, which sqeleton version, and any other information that might be relevant to this bug.
Make sure to include the following (minus sensitive information):

data-diff (0.3.1)
python 3.8

Output : 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexandre/projects/test_data_diff/.venv/lib/python3.8/site-packages/data_diff/diff_tables.py", line 99, in __iter__
    for i in self.diff:
  File "/home/alexandre/projects/test_data_diff/.venv/lib/python3.8/site-packages/data_diff/diff_tables.py", line 225, in _diff_tables_wrapper
    raise error
  File "/home/alexandre/projects/test_data_diff/.venv/lib/python3.8/site-packages/data_diff/diff_tables.py", line 196, in _diff_tables_wrapper
    self._validate_and_adjust_columns(table1, table2)
  File "/home/alexandre/projects/test_data_diff/.venv/lib/python3.8/site-packages/data_diff/hashdiff_tables.py", line 99, in _validate_and_adjust_columns
    raise TypeError(f"Incompatible types for column '{c1}':  {col1} <-> {col2}")
TypeError: Incompatible types for column 'source':  Integer(precision=0, python_type=<class 'int'>) <-> UnknownColType(text='smallint')

Have I identified the problem and the source of the problem correctly? If so, how can I fix it?

**Comment by erezsh** [comment]
Hello,

Yes, it sounds like you identified the right problem.

We recently split the database logic into a project called Sqeleton. The definitions you seek can be found here:

- https://github.com/datafold/sqeleton/blob/master/sqeleton/databases/mysql.py#L55
- https://github.com/datafold/sqeleton/blob/master/sqeleton/databases/postgresql.py#LL57C5-L57C5
 
It should be very straight-forward to add `smallint` or `longtext` etc.

However `geometry`, `point` and `json` might be a bit more tricky.

Anyway, once we fix it in Sqeleton, I can make a new release so it's available in data-diff.

Let me know if you need any help getting it going!

**Comment by titou41** [comment]
Hello, 

Ok perfect, i'm gonna open a PR with the modification. Let's forget about  `geometry`, `point` and ` json ` for now, but i'll do all the others one. 

Thanks
