### ISSUE TITLE
Oracle connection doesn't have a port number

### ISSUE THREAD

**Issue by skaosYan** [datafold/data-diff#370]
Hi, 

Oracle connector connects to a default port 1521 only. Please add ability to specify port.

class Oracle(ThreadedDatabase):
    dialect = Dialect()
    CONNECT_URI_HELP = "oracle://<user>:<pass>@<host>/<database>"
    CONNECT_URI_PARAMS = ["database?"]

**Comment by alwyndsouza** [comment]
make changes in oracle.py file on line #163 #166 #167

/usr/local/lib/python3.9/site-packages/sqeleton/databases

161 class Oracle(ThreadedDatabase):
162     dialect = Dialect()
163     CONNECT_URI_HELP = "oracle://<user>:<password>@<host>:<port>/<database>"
164     CONNECT_URI_PARAMS = ["database?"]
165         
166     def __init__(self, *, host, database, port, thread_count, **kw):
167         self.kwargs = dict(dsn=f"{host}:{port}/{database}" if database else host, **kw)
168         
169         self.default_schema = kw.get("user").upper()
170     
171         super().__init__(thread_count=thread_count)
172

**Comment by skaosYan** [comment]
Hey, can this issue be fixed??

**Comment by alwyndsouza** [comment]
Thanks for fixing the issue . 
https://github.com/datafold/data-diff/pull/548
