### ISSUE TITLE
Add support for Vitess 

### ISSUE THREAD

**Issue by skaosYan** [datafold/data-diff#371]
Vitess https://vitess.io is a sharded solution on top of MySQL engine. It has it's own behaviour which doesn't allow to use data-diff, particularly any aggregate a bit more complicated than min/max/count (with CAST on top of the aggregate function) will fail:

Vitess:
```
mysql> SELECT cast(min(`JOB_ID`) as char), cast(max(`JOB_ID`) as char) FROM `jobs`;
ERROR 1105 (HY000): unsupported: in scatter query: complex aggregate expression

```

**Comment by qsliu2017** [comment]
Will this idea be accepted? If so I'd like to have a try since I recently work on a project like this

**Comment by dlawin** [comment]
> Will this idea be accepted? If so I'd like to have a try since I recently work on a project like this

We would definitely accept contributions here!

**Comment by skaosYan** [comment]
Hi, any updates for this issue?

**Comment by dlawin** [comment]
@skaosYan We (the repo maintainers) are hesitant to add additional connectors, but if there was a community contribution with the understanding that the community/contributor would maintain it, I think we would accept the change.

We might mark the connector as "community maintained", "partially supported", or something like that.

@qsliu2017, is this something you're still interested in working on?

**Comment by qsliu2017** [comment]
@dlawin I won't be able to work on it at this time 😞

**Comment by dlawin** [comment]
I think it's best to close this request. If someone from the community would like to add this support, we're open to it, but it's not a priority for us at this time and could be added in a fork 

See https://github.com/datafold/data-diff/issues/371#issuecomment-1599622173
