### ISSUE TITLE
Support hard-coding column types 

### ISSUE THREAD

**Issue by RoderickJDunn** [datafold/data-diff#376]
**Use Case 1 - Using system column ROWID as primary key**
I need to Diff two tables (Oracle and Redshift) that don't have true primary key columns. The Oracle table is regularly replicated to Redshift, including the "ROWID" system identifier column, so that column also exists in Redshift though under a different name. When I supply "ROWID" as the key column to the Oracle table, the tool errors out due to not being able to find the column in Oracle's ALL_TAB_COLUMNS.

**Use Case 2 - Diffs between Views**
It would be useful to also have the ability to diff arbitrary views, or a View vs Table. Right now I don't think this is possible because the tool always tries to look up column types in the information schema.

**Describe the solution you'd like**
I'm working on a branch that allows you to override the column types so that we can use columns that don't show up in the DB's information schema (eg. ALL_TAB_MODIFICATIONS). Would love your feedback as to whether this is the right solution to the problem.

**Describe alternatives you've considered**
Another possible solution to **Use Case 2** is to allow for passing in the underlying tables that make up a view so that data-diff can look up the column types.

**Comment by erezsh** [comment]
1. Looks like ROWID always exists in Oracle, so we can automatically add it to every Oracle table schema.

2. Sounds like there should be a way to get the schema of views in Oracle? I didn't look deeply, but maybe something here - https://docs.oracle.com/cd/E18283_01/server.112/e17120/general011.htm

Overall, I understand why specifying the columns manually sounds like the easiest solution, but if we can solve this issue without any user interaction, that's much better!

**Comment by RoderickJDunn** [comment]
1. Love the idea of just adding rowid automatically to all oracle table schemas. Do you have any sort of timeline for when you might be able to work on that? If you don't have the cycles I can give it a shot
2. For this request, its actually Redshift connections that fail if you pass them a View instead of a table - unless I'm missing something. Is that expected? Haven't tried passing a View to Oracle connections yet.

**Comment by erezsh** [comment]
1. Doesn't seem like I'll have time for it soon, so I say give it a go!
2. We don't have support for views right now, so it makes sense that reading their schema might fail. But I think we should add it if we can.

**Comment by RoderickJDunn** [comment]
Ran into an issue trying to support for `ROWID` in Oracle. The datatype can contain unsupported chars `+` and `/`, in addition to alphanumerics. So I'm currently blocked by #355 - I'd like to help with that one possible but any chance you could give me a quick explanation of why other characters aren't supported? Is it just performance related?

**Comment by erezsh** [comment]
Yeah, there isn't actual a big reason not to support all ascii characters, other than it dilutes the search space and might cause "holes" when splitting it for regular alphanumerics. But I'm not sure that it's a big concern, I'm only trying to anticipate possible issues because I don't have proper tests for these scenarios.

Long story short, just adding all ascii characters should still work, but might degrade performance slightly, and it's unclear by how much. Perhaps it's not that significant, I'm just not sure.

It is also possible in theory to extend the range of accepted characters dynamically as we encounter new ones, but I think that would add some complications.

**Comment by RoderickJDunn** [comment]
Gotcha thanks for the clarification! What do you think of allowing the `pk_character_set` to be passed in by the user?

If i'm understanding correctly I could see this being beneficial in two ways
- Allows users to extend the list of characters beyond whats already supported (eg. with symbols like + / .)
- Allows users to restrict the list of characters if their PK only contains a much smaller set of chars - possibly resulting in a performance benefit?

**Comment by erezsh** [comment]
It's not a bad idea!

As I said, I'm not even sure that it's necessary. But it's definitely an easy cop-out to avoid finding out :)
