### ISSUE TITLE
Support using Postgresql `xmin` to compare lsn between databases

### ISSUE THREAD

**Issue by edjeffreys** [datafold/data-diff#377]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instead of comparing `updated_at` columns, it would be great to be able to use postgres's `xmin` to get the lsn for the record, and compare that against a column in the target database.

**Describe alternatives you've considered**
None

**Additional context**
Using debezium, we already store the lsn of each transaction in the target replica.

Having said this - for particularly large tables, this would not be viable as the lsn/txId may wraparound.

**Comment by erezsh** [comment]
Would allowing to compare expressions, in addition to plain column, be enough to address this issue?

**Comment by edjeffreys** [comment]
I suspect that would do it
