### ISSUE TITLE
Add support for views

### ISSUE THREAD

**Issue by erezsh** [datafold/data-diff#378]
It seems that in many databases, accessing the schemas of views works differently than schemas of tables. That means that currently data-diff won't be able to run on views in these databases.

We should add support for querying schemas of views whenever possible.

Mentioned in issue #376

**Comment by alexnikitchuk** [comment]
same issue with dbt models materialized as a views

**Comment by dlawin** [comment]
> same issue with dbt models materialized as a views

@alexnikitchuk Can you expand on the problem you're encountering by opening an issue here? https://github.com/datafold/data-diff/issues/new/choose

e.g. errors, database provider, etc.

**Comment by dlawin** [comment]
> > same issue with dbt models materialized as a views
> 
> Can you expand on the problem you're encountering by opening an issue here? https://github.com/datafold/data-diff/issues/new/choose
> 
> e.g. errors, database provider, etc.

@mariahjrogers If you're encountering this could you open an issue as well? This issue is very broad so I'd rather close it and focus on specifics
