### ISSUE TITLE
Wrong API key gives 404 instead of complaining about the API key

### ISSUE THREAD

**Issue by glebmezh** [datafold/data-diff#387]
**Describe the bug**
When you invoke `data-diff` in Cloud mode with a wrong API key, it gives a cryptic 404 error. I was lucky to have suspected the API key problem right away. Instead, it should give an error calling out that API key was rejected.
```
data-diff --dbt --cloud
Found 3 successful model runs from the last dbt command.
[08:47:55] ERROR - 404 Client Error: Not Found for url: https://app.datafold.com/api/v1/datadiffs
```

- data-diff v0.4.0
- OS: MacOS 12.5
- Python 3.10.0

**Comment by dlawin** [comment]
A 403 response from the API would be more appropriate

**Comment by dlawin** [comment]
Addressed in https://github.com/datafold/data-diff/pull/467

**Comment by dlawin** [comment]
Reopening as this is still occurring, appears to stem from inconsistent responses from the api when an incorrect key is used
