### ISSUE TITLE
data-diff --dbt --cloud creates accurate, but reversed, diff results

### ISSUE THREAD

**Issue by leoebfolsom** [datafold/data-diff#388]
**Describe the bug**
Diff results in the Datafold should be switched--prod should be on the left, dev on the right. Same with the CLI printout.

<img width="946" alt="Screenshot 2023-02-10 at 15 52 31" src="https://user-images.githubusercontent.com/1799931/218223551-0ac052ee-da85-4614-81b9-6548243481d2.png">

<img width="912" alt="Screenshot 2023-02-10 at 15 54 32" src="https://user-images.githubusercontent.com/1799931/218223645-e369f6ec-3aa9-4a3b-a992-05831dd2ef7e.png">

**Comment by dlawin** [comment]
I think this can be resolved easily here: https://github.com/datafold/data-diff/blob/29bfa73105260e680d7769b5dd7bc993c637204a/data_diff/dbt.py#L194

`diff_vars.dev_path` -> table2, `diff_vars.prod_path` -> table1

Assuming that is what determines the order in the UI

**Comment by dlawin** [comment]
Requires an api key to test, so likely a change for Datafold vs. community.
