### ISSUE TITLE
Add support for Redshift when using --dbt

### ISSUE THREAD

**Issue by Osama-BI** [datafold/data-diff#396]

**Comment by erezsh** [comment]
@Osama-BI We already support redshift. Does that not work?

**Comment by Osama-BI** [comment]
I read this on the documentation page, so I thought Redshift is not supported

![Screenshot_2023-02-16-20-19-09-51.jpg](https://user-images.githubusercontent.com/108630318/219453663-69b54cf7-9128-4b4c-87eb-4895646a3589.jpg)

**Comment by mattppal** [comment]
Perhaps the title should be "Support Redshift for dbt diffs"

`[10:36:14] ERROR - Provider redshift is not yet supported for dbt diffs`

**Comment by lindsaymurphy4** [comment]
Would also like this for dbt diffs :) 👍

**Comment by dlawin** [comment]
Hi folks, we're adding redshift support in our next release so I am going to resolve this issue https://github.com/datafold/data-diff/pull/382
