### ISSUE TITLE
Unexpected behavior using min_key/max_key

### ISSUE THREAD

**Issue by RoderickJDunn** [datafold/data-diff#401]
**Describe the bug**
When I pass in the `min_key` and/or `max_key` parameters, I would expect data-diff to skip the `query_key_range` step since it already knows the min/max keys. 

For example, if I want to restrict the account ID range by passing in `min_key=000000000001` and `max_key=R90909RDD099`, the tool still executes `query_key_range` with a query like this:
```
SELECT cast(min("ACCT_ID") as varchar(1024)), cast(max("ACCT_ID") as varchar(1024)) 
FROM "accounts" 
WHERE ("ACCT_ID" >= '000000000001') AND ("ACCT_ID" < 'R90909RDD099')
```

IMO this query should've been skipped since the user already told data-diff the min/max values for ACCT_ID.

This query can be slow for large tables, so it would be great to bypass it if the min/max keys are already known.

**Describe the environment**
Ubuntu
data-diff version: [608312d944ada6ba07c810f25a4bd638933c8fc1](https://github.com/datafold/data-diff/commit/608312d944ada6ba07c810f25a4bd638933c8fc1)

**Comment by erezsh** [comment]
I agree. We should only query for these values if they are set to None.
