### ISSUE TITLE
Stop `data-diff` when maximum time or # different records is exceeded

### ISSUE THREAD

**Issue by JCZuurmond** [datafold/data-diff#402]
**Is your feature request related to a problem? Please describe.**

We run `data-diff` for many tables. Sometimes there are a lot of differences between the diffed tables. If so, the data diff for this tablepair might take a very long time (multiple hours). I prefer to skip this diff at a certain point, e.g., when a maximum diff time or # different records is exceeded. For such a diff, I do not care which records differ precisely, I am ok with knowing that this table is very off.

**Describe the solution you'd like**

Define a:
- maximum diff time
- OR, a maximum # different records
- OR, a maximum % different records

If this threshold is exceeded, the diff is aborted, with a WARNING or ERROR message, and maybe an Exception.

**Describe alternatives you've considered**

I run `data-diff` programmatically and built this feature myself in the Python script that calls `data-diff`. This did not work as I hoped because `data-diff` uses a `ThreadPool` that continued with the diff after I broke out of the [`diff_tables`](https://data-diff.readthedocs.io/en/latest/python-api.html#data_diff.diff_tables) iterable.

**Additional context**

**Comment by JCZuurmond** [comment]
I am still interested in this issue

**Comment by dlawin** [comment]
Agreed this would be very useful. 

We just added some automation here yesterday to help us wrangle the open issues list, thanks for bearing with us

**Comment by JCZuurmond** [comment]
☝️

**Comment by dungkhuc** [comment]
This is very useful as as it is data-diff would otherwise just stay stuck for many hours in our automation script if there are a big number of changes.

**Comment by glebmezh** [comment]
@JCZuurmond @dungkhuc ,

I'm sorry for the delay in following up on this. Thank you for taking the time to raise this issue!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support.

If that's of interest, over the past few months, we have rewritten the diffing engine in Datafold Cloud and solved many issues that existed in this package. In particular, we implemented sampling, per-column diff limits, and real-time result updates to help with the problem you are describing.

-Gleb
