### ISSUE TITLE
"Columns exclusive to table A/B" confusing

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#420]
**Describe the bug**
When I add a column to my dev model and run a `data-diff --dbt`, the new column is called out like:
"Columns exclusive to table A"

This is confusing, as we now display the "dev" model on the right side of the output:
<img width="619" alt="Screenshot 2023-02-26 at 6 56 22 PM" src="https://user-images.githubusercontent.com/11282254/221454347-daf17d03-7e7b-44dc-bd03-0bc77b5edb95.png">
(new_column is added to dev)

**Comment by kylemcnair** [comment]
I’ll take a stab at this tomorrow
