### ISSUE TITLE
@ in redshift password

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#428]
**Describe the bug**
When my password includes an "@", I'm unable to use the data-diff CLI, as it causes the url to be parsed incorrectly.

I have only experienced this on redshift, but it likely is an issue for other providers

Make sure to include the following (minus sensitive information):
`data-diff redshift://user:@Password@redshift:5439/dev schema.table redshift://user:@Password@redshift:5439/dev schema.table`
-> `failed: FATAL:  password authentication failed for user "Password"`

Quoting, escape sequences, and url escape codes do not resolve.

A .toml file and the `--conf` option should be a workaround, but I have not had a chance to test that yet:
https://docs.datafold.com/os_diff/how_to_use/how_to_use_with_toml

**Comment by jbonatakis** [comment]
I have also experienced this issue. I tried passing in my password via an environment variable, URL encoding the password, escaping the `@`, and the toml file -- nothing worked.

**Comment by dlawin** [comment]
@jbonatakis 
> I have also experienced this issue. I tried passing in my password via an environment variable, URL encoding the password, escaping the `@`, and the toml file -- nothing worked.

I was able to workaround this with a toml file. Or are you running into this while trying to use the `--dbt` feature?

**Comment by jbonatakis** [comment]
Hmm no I'm definitely still having issues with the toml file. I'm not using the `--dbt` flag. The same user/password combo connects fine via DataGrip/dbeaver but not with data-diff. When I swap out for another user/password combo without the `@` in the password, changing nothing else, I can connect. I'll try to provide some more specific info later.
