### ISSUE TITLE
Support dbt 1.4.2 and above

### ISSUE THREAD

**Issue by williebsweet** [datafold/data-diff#433]
As noted in a [recent PR](https://github.com/datafold/data-diff/pull/382#issue-1573390627), dbt-core’s manifest.json files do not align with the posted schema for dbt-core >= 1.4.2, so it’ll take some additional work to support 1.4.2, 1.4.3, 1.4.4.

**Comment by dlawin** [comment]
Related: https://github.com/dbt-labs/dbt-core/issues/7119
