### ISSUE TITLE
Snowflake materialize tables are created with columns in lowercase

### ISSUE THREAD

**Issue by rickokin** [datafold/data-diff#441]
When running a data-diff using the -m option to create a table of the diffs (also using -v), the table that gets created has all of the columns in lowercase.  This results in having to quote the column names in a select statement to look at the data in the created table.  It would be easier if the table was created using uppercase column names and then the select statement would not require double quotes and would support referencing the column names in either lowercase or uppercase.

This is for a snowflake database table.

**Comment by rickokin** [comment]
Please keep this open and address the issue.

**Comment by dlawin** [comment]
Thanks for reporting this @rickokin, we're not currently working on this but may in the future, in the meantime we'd happily accept a community contribution
