### ISSUE TITLE
ERROR - Table appears to be empty

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#449]
**Describe the bug**
Empty table exits a `--dbt` diff early

```
    data-diff --dbt
Found 4 successful model runs from the last dbt command.
duckdb_demo.prod.dim_orgs <> duckdb_demo.dev.dim_orgs
No row differences

duckdb_demo.prod.fct_monthly_financials <> duckdb_demo.dev.fct_monthly_financials
No row differences

[11:36:47] ERROR - Table appears to be empty
```

```
data_diff/table_segment.py", line 255, in query_key_range
    raise ValueError("Table appears to be empty")
ValueError: Table appears to be empty
```

Diffing should continue in this scenario, maybe switch this exception to a logger warning

**Comment by sceniclife** [comment]
I agree that diffing an empty table should still proceed or at least an option to allow empty table diffing.

**Comment by pep4eto1211** [comment]
Is there some new around this? I have a case where sometimes one of the tables will be empty and other not- and I need to have it correctly show those as differences.
