### ISSUE TITLE
Expand --cloud output

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#460]
The `--dbt --cloud` output is extremely basic at the moment:
```
Running with data-diff=0.5.0

INTEGRATION.BEERS_test_custom_schema.simple_example <> DEV.DBT_DEV_DAN_test_custom_schema.simple_example
    Diff in progress:
    https://app.datafold.com/datadiffs/<diff_id>/overview

INTEGRATION.BEERS.simple_example_downstream <> DEV.DBT_DEV_DAN.simple_example_downstream
    Diff in progress:
    https://app.datafold.com/datadiffs/<diff_id>/overview

Diffs Complete!
```

**Describe the solution you'd like**
Add functionality to poll `/api/v1/datadiffs/<diff_id>/summary_results` and also display high level results in the command line

**Comment by dlawin** [comment]
@williebsweet feel free to change/add anything

**Comment by dlawin** [comment]
I'm addressing https://github.com/datafold/data-diff/issues/387 alongside this issue

**Comment by williebsweet** [comment]
@dlawin Is there a PR for this?
