### ISSUE TITLE
Add additional debugging information for artifacts paths

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#499]
It's sometimes unclear which dbt artifacts data-diff is parsing

Output the files/paths being used in the debug logger

Probably makes sense to log the path any time we're doing a `with open` https://github.com/datafold/data-diff/blob/25692cbfb73d1049d55697ae8cff6f775caed329/data_diff/dbt_parser.py#L70

**Comment by dlawin** [comment]
Example:
`Parsing file /blah/analytics/target/run_results.json`

**Comment by MalanB** [comment]
Hey folks, can I work on this issue?
