### ISSUE TITLE
During installation dependency check failed for poetry-code package , even though we have installed that package

### ISSUE THREAD

**Issue by sureshhealth** [datafold/data-diff#512]
During installation dependency check failed for poetry-code package , even though we have installed that package.
 **command Used** 
Processing d:\datafiles\downloads\data-diff-0.3.2.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files\python39\python.exe' 'C:\Users\HSS-eRef-SQL-QRM\AppData\Local\Temp\2\pip-standalone-pip-h9gfjdag\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\HSS-eRef-SQL-QRM\AppData\Local\Temp\2\pip-build-env-mlkvnx65\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i [https://pypi.org/simple](https://urldefense.com/v3/__https:/pypi.org/simple__;!!Lav448XFWxY!61w9oAiS0MOzK3w3u5KpvkABoXuPe_tUPiY2DGNWjhG3CjxjC9hBkyQHxMIdcIn9gWJB0zkyuUA1cSMiH8nxqgk$) -- 'poetry-core>=1.0.0'

pip list results - poetry-core is available
c:\Program Files\Python39\Lib\site-packages>pip list
Package                Version
---------------------- -------
ansicon                1.89.0
appdirs                1.4.4
arrow                  1.1.0
asgiref                3.3.1
blessed                1.18.0
data-anonymizer-mapper 0.1.0
distlib                0.3.1
Django                 3.1.7
django-cors-headers    3.7.0
django-filter          2.4.0
django-mssql-backend   2.8.1
django-picklefield     3.0.1
django-q               1.3.6
djangorestframework    3.12.2
Faker                  6.6.3
filelock               3.0.12
firebird-base          1.2.0
firebird-driver        1.1.0
flit-core              3.8.0
intreehooks            1.0
jinxed                 1.1.0
mssql-django           1.0b1
numpy                  1.20.1
pandas                 1.2.3
pip                    21.1.2
poetry-core            1.5.2
protobuf               3.15.8
pyodbc                 4.0.30
python-dateutil        2.8.1
pytoml                 0.1.21
pytz                   2021.1
setuptools             56.0.0
six                    1.15.0
SQLAlchemy             1.3.23
sqlescapy              1.0.1
sqlparse               0.4.1
text-unidecode         1.3
unicode                2.8
urllib3                1.26.3
virtualenv             20.4.2
wcwidth                0.2.5

**Describe the environment**

Describe which OS you're using, which data-diff version, and any other information that might be relevant to this bug.
Windows environment

**Comment by dlawin** [comment]
Does this occur when running `pip install 'data-diff==0.3.2'`?
