### ISSUE TITLE
Support UUID x Text comparison

### ISSUE THREAD

**Issue by MattDelac** [datafold/data-diff#513]
**Describe the bug**
Matt Delac [6:38 PM](https://locallyoptimistic.slack.com/archives/C03HUNGQV0S/p1680824280722009)
Hi 
[@Erez Shinan](https://locallyoptimistic.slack.com/team/U03JGTA1H2Q), follow up of [my PR](https://github.com/datafold/sqeleton/pull/37).
It sounds like we also need to support UUID x Text?
> TypeError: Incompatible types for column 'owner_id':  String_UUID() <-> Text()

On my use case, it happens between MySQL UUID <> Redshift Text.
I am not sure where UUID fits the class Dialect object though

**Describe the environment**

Describe which OS you're using, which sqeleton version, and any other information that might be relevant to this bug.

**Comment by timothyhinh79** [comment]
Any update on this issue? I'm seeing this happen on Postgres where the column is being converted to "String_UUID" in one table, but is classified as "Text" in the other table due to detection of non-UUID values.

**Comment by dlawin** [comment]
> Any update on this issue? I'm seeing this happen on Postgres where the column is being converted to "String_UUID" in one table, but is classified as "Text" in the other table due to detection of non-UUID values.

Hi @timothyhinh79, we're not currently working on this but may in the future, in the meantime we'd happily accept a community contribution

**Comment by ramdharam** [comment]
@dlawin - I had this exact issue when comparing snowflake and postgres and I was able to come up with a simple approach that will overcome this issue in my fork. May be that can help. I will push it out and hopefully it can overcome your issue too.

**Comment by MattDelac** [comment]
> @dlawin - I had this exact issue when comparing snowflake and postgres and I was able to come up with a simple approach that will overcome this issue in my fork. May be that can help. I will push it out and hopefully it can overcome your issue too.

Hey did you get that working?

**Comment by MattDelac** [comment]
I still encounter this issue on the latest version (0.9.9) ...

**Comment by mrn3** [comment]
I think once we get https://github.com/datafold/data-diff/issues/762 worked out, it will resolve this issue too

**Comment by dlawin** [comment]
> I still encounter this issue on the latest version (0.9.9) ...

@MattDelac do you get this warning?

`Mixed UUID/Non-UUID values detected in column {'.'.join(table_path)}.{col_name}, disabling UUID support`

**Comment by MattDelac** [comment]
> > I still encounter this issue on the latest version (0.9.9) ...
> 
> @MattDelac do you get this warning?
> 
> `Mixed UUID/Non-UUID values detected in column {'.'.join(table_path)}.{col_name}, disabling UUID support`

No now I get  the following when I compare UUID (MySQL) to BINARY (Snowflake)
<img width="1501" alt="image" src="https://github.com/datafold/data-diff/assets/18557047/5f9f4f3d-052c-44f3-902f-ccf118e87de0">

**Comment by glebmezh** [comment]
Hi @MattDelac,

I'm sorry for the delay in following up on this. Thank you for taking the time to open this PR!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support.

W.r.t UUID x Text diffing. If that helps at all, we currently support it in Datafold Cloud with the caveat that upper/lower casing and "-" characters should match.

-Gleb
