### ISSUE TITLE
Trino connection string password

### ISSUE THREAD

**Issue by dot2dotseurat** [datafold/data-diff#514]
The trino connection string defined in the database connection does not contain an arg for a password.
https://github.com/datafold/sqeleton/blob/6c532733e1a3efe329b573691d3d9d18dcf4f410/sqeleton/databases/trino.py#L38

However, a password is referenced as part of the connection string in the [docs](https://docs.datafold.com/os_diff/databases_we_support/). 
`trino://<username>:<password>@<hostname>:8080/<database>`

This results in the following error when trying to connect using a password (as expected based on the implementation). 
`TypeError: __init__() got an unexpected keyword argument 'password'`

Without the password arg, the db cannot connect. 

If I'm not mistaken, the implementation should be or am I missing something?
`CONNECT_URI_HELP = "trino://<user>:<password>@<host>/<catalog>/<schema>"`

**Comment by jkleinkauff** [comment]
I'm facing the same problem.

**Comment by skm235** [comment]
Please remove the password and try. You are using 8080 as port, so password not required.
