### ISSUE TITLE
Support automatic sampling in --dbt (non --cloud)

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#520]
When diffing locally I would like to diff against sampled data. When a table is large this would increase performance considerably, and would still give me an understanding of the changes.

This will be a larger lift, but should work interchangeably with the `--cloud` feature described here:
https://github.com/datafold/data-diff/issues/519

**Comment by mimoyer21** [comment]
Would still love this feature, so commenting to keep this issue open.

**Comment by dlawin** [comment]
> Would still love this feature, so commenting to keep this issue open.

Agreed, I think I need to add a tag to make some issues immune to the stale bot
