### ISSUE TITLE
Several dependencies being "Extras" makes installation complex

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#526]
**Is your feature request related to a problem? Please describe.**
There are several ways to install data-diff depending on the usage and database provider.

Examples:
`--dbt` user on snowflake: `pip install data-diff 'data-diff[snowflake,dbt]'`
`--dbt` user on bigquery: `pip install data-diff 'data-diff[dbt]' google-cloud-bigquery`
non `--dbt` user on postgres: `pip install data-diff 'data-diff[postgres]'`
... etc.

**Describe the solution you'd like**
Reduce the number of pip "extras" to simplify installation

Balancing the tradeoff of increasing package size

**Additional context**
Installation instructions: https://docs.datafold.com/development_testing/open_source

**Comment by mariahjrogers** [comment]
I will second this by adding that it doesn't seem possible to manage the install of data-diff and its extras via Poetry if you need more than one of the extras...

I tried doing `poetry add 'data-diff[redshift,dbt]` and it just doesn't work.

`poetry add`'ing them separately overwrites the entry in the `pyproject.toml` with the second one added, and adding them together causes the resolver to hang indefinitely.

Either one of the extras by itself works fine 😂
