### ISSUE TITLE
Add support for SQLite

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#536]
Having SQLite in addition to DuckDB would make it super easy to show off cross db diffing without any external dependencies

cc: @dbeatty10

**Comment by dlawin** [comment]
This could also simplify cross-db CI tests, as we could remove the need for external databases

**Comment by dbeatty10** [comment]
@dlawin would you be open to either removing the `stale` label or maybe even adding `stale_immune`?

**Comment by glebmezh** [comment]
All - I'm sorry for the delay in following up on this. Thank you for taking the time to raise this issue!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support.

-Gleb
