### ISSUE TITLE
Commas for number output

### ISSUE THREAD

**Issue by kylemcnair** [datafold/data-diff#538]
**Is your feature request related to a problem? Please describe.**
In a recent data-diff, with the numbers being large, I found it a little hard to glean info.

```
ANALYTICS.ANALYTICS.ORG_ACTIVITY_STREAM <> DEV.DBT_DEV_KYLE.ORG_ACTIVITY_STREAM 

  Rows Added    Rows Removed
------------  --------------
        1386           86573

Updated Rows: 1558080
Unchanged Rows: 2999582

Values Updated:
ORG_NAME: 14
USER_ID: 100
CUSTOM_PROPERTIES: 86
ACTIVITY_REPEATED_AT: 504400
ORG_ID: 14
ACTIVITY: 0
EVENT_TIMESTAMP: 0
USER_EMAIL: 100
ORG_KEY: 14
ACTIVITY_OCCURRENCE: 1413643 
```

**Describe the solution you'd like**
I think formatting numbers with commas is an easy win.

**Describe alternatives you've considered**
* add percentages
  * I think % everywhere can get too busy, but I think even topline % changes for row would help

This is a little more subjective and I'm gonna skip for now.

**Comment by dlawin** [comment]
@kylemcnair do you still want to work on this one? If not I can take it

**Comment by glebmezh** [comment]
Hi @kylemcnair,

I'm sorry for the delay in following up on this. Thank you for taking the time to raise this issue!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support.

If that's of interest, over the past few months, we have rewritten the diffing engine in Datafold Cloud and solved many issues that existed in this package.

-Gleb
