### ISSUE TITLE
`FETCH NEXT {limit} ROWS` is not supported

### ISSUE THREAD

**Issue by qsliu2017** [datafold/data-diff#549]
**Describe the bug**

With Oracle 11.2, data-diff reports
```
ERROR - ORA-00933: SQL command not properly ended
```

Currently, data-diff uses `FETCH NEXT {limit} ROWS ONLY` to perform offset_limit for Oracle. However it is not supported until Oracle 12.1. Thus some steps (e.g. `Database._refine_coltypes`) of data-diff will fail. Before then, Oracle used [`ROWNUM` to limit result](https://blogs.oracle.com/connect/post/on-rownum-and-limiting-results), which is a `WHERE` expr.

**Describe the environment**

data-diff version: 0.7.4
Oracle version: <12.1

**Comment by zhangbobo131415** [comment]
i use oracle 11,i have the same problem. so how to resolve this? the resolution is where rownum < ${limit} ?

**Comment by qsliu2017** [comment]
> i use oracle 11,i have the same problem. so how to resolve this? the resolution is where rownum < ${limit} ?

I modify https://github.com/datafold/data-diff/blob/ea68fb51670785812f8eb10382ccec427566b55a/data_diff/sqeleton/databases/oracle.py#L111 to
```python
 return ""
```

**Comment by zhangbobo131415** [comment]
> > i use oracle 11,i have the same problem. so how to resolve this? the resolution is where rownum < ${limit} ?
> 
> I modify
> 
> https://github.com/datafold/data-diff/blob/ea68fb51670785812f8eb10382ccec427566b55a/data_diff/sqeleton/databases/oracle.py#L111
> 
> to
> ```python
>  return ""
> ```

so, if the table has 100k rows, return "" can work ?

**Comment by zhangbobo131415** [comment]
I rarely use  python，i am trying to understand it.
