### ISSUE TITLE
Incorrect difference when comparing varchar key between Oracle and RDS Postgres

### ISSUE THREAD

**Issue by skmanchala** [datafold/data-diff#550]
Giving inaccurate differnce when comparing the varchar key value  between  a table in Oracle and RDS Postgres.

**Comment by skmanchala** [comment]
Orgin difference shows correct , destination difference  just dumps the whole key list even though they exist

**Comment by chandu-chai** [comment]
The same issue I found between Postgres and BigQuery. More details are [here](https://github.com/datafold/data-diff/issues/532).

**Comment by dlawin** [comment]
relates to https://github.com/datafold/data-diff/issues/550

**Comment by dlawin** [comment]
> No Worries, i have found a alternate way of finding the differences without the data-diff. The package will be of no use if it cannot follow some basic rules when comparing..

Hey @skmanchala can you add some detail?

This is not enough to be actionable on its own:
> Giving inaccurate differnce when comparing the varchar key value between a table in Oracle and RDS Postgres.
> Orgin difference shows correct , destination difference just dumps the whole key list even though they exist

However this scenario may become apparent in the resolution of #550

**Comment by skmanchala** [comment]
We have a Varchar primary key in both RDS  Postgrest and Oracle which i am using to compare the data, as mentioned previously , the record in source not in target shows up correcly  but after that it shows all the records in destination not present in source

**Comment by glebmezh** [comment]
Hi @skmanchala,

I'm sorry for the delay in following up on this. Thank you for taking the time to raise this issue!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support.

If that's of interest, over the past few months, we have rewritten the diffing engine in Datafold Cloud and solved many issues that existed in this package's diffing algorithm.

-Gleb
