### ISSUE TITLE
HashDiffer algorithm

### ISSUE THREAD

**Issue by pmuntianu** [datafold/data-diff#563]
Hello. I would like to ask a question regarding the algorithm for the hash diff. Is there any explanation anywhere how it works between two databases? In particular I am curious about its internal implementation whether it is downloading all hashed rows to the computer or doing hash of the hash to limit the amount of downloaded data?

Lets say that there are two tables with 1M records on each side. Would it download 2M hashes from both databases or it will download less to the instance where it is running?

**Comment by pmuntyanu** [comment]
Found it. The answer is no, it will try to download less than 2M records, but it depends on the amount of segments and amount of discrepancies: [technical-explanation.md](https://github.com/datafold/data-diff/blob/master/docs/technical-explanation.md)
