### ISSUE TITLE
After installing `data-diff`, `Invalid value for '--profiles-dir': Path '~/.dbt/' does not exist.` error gets thrown despite this path existing

### ISSUE THREAD

**Issue by garfieldthesam** [datafold/data-diff#571]
**Describe the bug**
I used `pip` to `upgrade` multiple dependencies, including `dbt-databricks` and `dbt-core` so I could install [data-diff](https://github.com/datafold/data-diff#readme).

After installing it, `dbt run` and other CLI commands throw this error: `Error: Invalid value for '--profiles-dir': Path '~/.dbt/' does not exist.`

However, this path exists. When I run `dbt run --profiles-dir ~/.dbt/` the job completes without error.

I've confirmed that my `~/.zshrc` contains `export DBT_PROFILES_DIR="path/to/.dbt"` and restarted Terminal.

This error is thrown whether submitting a bigquery job or a databricks job.

What could be causing this? :thinking:

**Describe the environment**

MacOS Ventura 13.1
`dbt-core` vsn 1.5.0
`dbt-databricks` vsn 1.5.1
`data-diff` vsn 0.7.5

**Comment by garfieldthesam** [comment]
Resolved issue on my end; discussion on the dbt community forum [here](https://discourse.getdbt.com/t/invalid-value-for-profiles-dir-path-dbt-does-not-exist-error-gets-thrown-despite-this-path-existing/8228/4). Resolved by finding the line `export DBT_PROFILES_DIR="~/.dbt/"` in my `.zshrc`, deleting it, and ensuring only the line `export DBT_PROFILES_DIR="/absolute/path/to/.dbt/` 

One or more of the following seems to have happened, not sure which:
1. After upgrading packages, the line `export DBT_PROFILES_DIR="~/.dbt/"` was added to my `~/.zshrc` file
2. dbt lost the ability to interpret the relative path `~/.dbt.` as a valid file path
3. dbt is now using some other account's home folder that does not have a `/.dbt/` subfolder 

To answer your question, I did not run `dbt debug --config-dir` before fixing the issue, but when running `echo $DBT_PROFILES_DIR` it returned `~/.dbt/`. But since updating my zsh config it now returns the absolute path and works as expected. Feel free to close or ask any follow up questions!

**Comment by garfieldthesam** [comment]
Actually I just realized it's very easy to revert the fix and run `dbt debug --config-dir`. Here's what it returns when `DBT_PROFILES_DIR="~/.dbt/"` is re-added to the bottom of my zsh config:

```
23:36:35  Running with dbt=1.5.0
23:36:35  To view your profiles.yml file, run:
```

Here's what `dbt debug` returns:
```
23:38:43  Running with dbt=1.5.0
23:38:43  dbt version: 1.5.0
23:38:43  python version: 3.9.6
23:38:43  python path: /Library/Developer/CommandLineTools/usr/bin/python3
23:38:43  os info: macOS-13.1-arm64-arm-64bit
23:38:43  Using profiles.yml file at ~/.dbt/profiles.yml
23:38:43  Using dbt_project.yml file at /path/to/repo/dbt_project.yml
23:38:43  Configuration:
23:38:43    profiles.yml file [ERROR not found]
23:38:43    dbt_project.yml file [OK found and valid]
23:38:43  Required dependencies:
23:38:43   - git [OK found]

23:38:43  1 check failed:
23:38:43  dbt looked for a profiles.yml file in ~/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile
```

**Comment by kylemcnair** [comment]
@garfieldthesam glad you figured it out! wonder if it's related to that 1.5 core bug Doug mentioned.

I'm going to close this issue, but let us know if you run into any other issues.
