### ISSUE TITLE
Non-integer IDs

### ISSUE THREAD

**Issue by joeltone** [datafold/data-diff#59]
I have several tables that use GUIDs for their primary key.  Can data-diff test these tables or only tables where the primary key is an integer?

**Comment by sirupsen** [comment]
@joeltone are you using the UUID type in Postgres? What's source/target database and type?

**Comment by joeltone** [comment]
Both databases are in Snowflake and I'm just using a string data type for the ids.

**Comment by joeltone** [comment]
I'll see what I can find.  Thanks for the help!

**Comment by sirupsen** [comment]
Below's a really hack prototype of how it's possible to support string keys, assuming a random distribution (as UUIDs would have). Probably has some crucial bugs and off-by-ones, but I think directionally it'd work.

```patch
diff --git a/data_diff/database.py b/data_diff/database.py
index dc208b6..cafeb5f 100644
--- a/data_diff/database.py
+++ b/data_diff/database.py
@@ -216,7 +216,7 @@ class Database(AbstractDatabase):
         rows = self.query(self.select_table_schema(path), list)
 
         # Return a dict of form {name: type} after canonizaation
-        return {row[0].lower(): self._parse_type(*row[1:]) for row in rows}
+        return {row[0]: self._parse_type(*row[1:]) for row in rows}
 
     @lru_cache()
     def get_table_schema(self, path: DbPath) -> Dict[str, ColType]:
diff --git a/data_diff/diff_tables.py b/data_diff/diff_tables.py
index e25bf15..c25b7f2 100644
--- a/data_diff/diff_tables.py
+++ b/data_diff/diff_tables.py
@@ -28,8 +28,18 @@ def safezip(*args):
 
 
 def split_space(start, end, count):
-    size = end - start
-    return list(range(start, end, (size + 1) // (count + 1)))[1 : count + 1]
+    space = []
+    for c in range(ord('0'), ord('9')):
+        space.append(start + chr(c))
+
+    for c in range(ord('a'), ord('f')):
+        space.append(start + chr(c))
+
+    print(space)
+    return space
+
+    # size = end - start
+    # return list(range(start, end, (size + 1) // (count + 1)))[1 : count + 1]
 
 
 def parse_table_name(t):
@@ -96,9 +106,9 @@ class TableSegment:
 
     def _make_key_range(self):
         if self.min_key is not None:
-            yield Compare("<=", str(self.min_key), self._key_column)
+            yield Compare("<=", f"'{self.min_key}'", self._key_column)
         if self.max_key is not None:
-            yield Compare("<", self._key_column, str(self.max_key))
+            yield Compare("<", self._key_column, f"'{self.max_key}'")
 
     def _make_update_range(self):
         if self.min_update is not None:
@@ -266,8 +276,8 @@ class TableDiffer:
         mins, maxs = zip(*key_ranges)
 
         # We add 1 because our ranges are exclusive of the end (like in Python)
-        min_key = min(map(int, mins))
-        max_key = max(map(int, maxs)) + 1
+        min_key = '0' # min(mins)
+        max_key = 'f' # max(maxs) # + 1
 
         table1 = table1.new(min_key=min_key, max_key=max_key)
         table2 = table2.new(min_key=min_key, max_key=max_key)
@@ -275,7 +285,7 @@ class TableDiffer:
         logger.info(
             f"Diffing tables | segments: {self.bisection_factor}, bisection threshold: {self.bisection_threshold}. "
             f"key-range: {table1.min_key}..{table2.max_key}, "
-            f"size: {table2.max_key-table1.min_key}"
+            # f"size: {table2.max_key-table1.min_key}"
         )
 
         return self._bisect_and_diff_tables(table1, table2)
@@ -283,8 +293,10 @@ class TableDiffer:
     def _validate_and_adjust_columns(self, table1, table2):
         for c in table1._relevant_columns:
             if c not in table1._schema:
+                print(table1._schema)
                 raise ValueError(f"Column '{c}' not found in schema for table {table1}")
             if c not in table2._schema:
+                print(table2._schema)
                 raise ValueError(f"Column '{c}' not found in schema for table {table2}")
 
             # Update schemas to minimal mutual precision
@@ -307,7 +319,7 @@ class TableDiffer:
 
         if max_rows is None:
             # We can be sure that row_count <= max_rows
-            max_rows = table1.max_key - table1.min_key
+            max_rows = 10000000000 # table1.max_key - table1.min_key
 
         # If count is below the threshold, just download and compare the columns locally
         # This saves time, as bisection speed is limited by ping and query performance.
@@ -339,7 +351,7 @@ class TableDiffer:
         logger.info(
             ". " * level + f"Diffing segment {segment_index}/{segment_count}, "
             f"key-range: {table1.min_key}..{table2.max_key}, "
-            f"size: {table2.max_key-table1.min_key}"
+            # f"size: {table2.max_key-table1.min_key}"
         )
 
         (count1, checksum1), (count2, checksum2) = self._threaded_call("count_and_checksum", [table1, table2])
diff --git a/tests/common.py b/tests/common.py
index 34e3b5b..d95f610 100644
--- a/tests/common.py
+++ b/tests/common.py
@@ -6,11 +6,11 @@ import logging
 logging.basicConfig(level=logging.WARN)
 
 TEST_MYSQL_CONN_STRING: str = "mysql://mysql:Password1@localhost/mysql"
-TEST_POSTGRES_CONN_STRING: str = None
-TEST_SNOWFLAKE_CONN_STRING: str = None
+TEST_POSTGRES_CONN_STRING: str = "postgres://postgres:Password1@localhost/postgres"
+TEST_SNOWFLAKE_CONN_STRING: str = "snowflake://erez:erez27Snow@bya42734/xdiffdev/TEST1?warehouse=INTEGRATION"
 TEST_BIGQUERY_CONN_STRING: str = None
-TEST_REDSHIFT_CONN_STRING: str = None
-TEST_ORACLE_CONN_STRING: str = None
+TEST_REDSHIFT_CONN_STRING: str = "redshift://admin:gcn-BHC7peq9dyhhtz@localhost:5439/dev"
+TEST_ORACLE_CONN_STRING: str = None # "oracle://oracle:TzR2n6e4i7ULgSzN@127.0.0.1/ORACLE"
 
 
 try:

```

**Comment by sirupsen** [comment]
@kning thanks for the feedback! This is actually already better in master as per https://github.com/datafold/data-diff/pull/58

The schema is now checked (for a bunch of other reasons too), and the error raised now is:

```
ValueError: Column 'id' not found in schema for table TableSegment(database=<data_diff.database.Postgres object at 0x103adce50>, table_path=('no_id',), key_column='id', update_column=None, extra_columns=(), min_key=None, max_key=None, min_update=None, max_update=None, quote_columns=True, _schema={'lol': UnknownColType(text='character varying')})
```

**Comment by leoebfolsom** [comment]
Thirded. I've got primarily GUIDs.

**Comment by erezsh** [comment]
Just FYI, this is a priority issue for us. I hope to have a PR ready by the end of the week.

**Comment by erezsh** [comment]
@leoebfolsom @MattDelac @joeltone Can you please tell me what type do you use for your UUID column, and in which database? I want to make sure we cover it in our tests.

**Comment by MattDelac** [comment]
> @leoebfolsom @MattDelac @joeltone Can you please tell me what type do you use for your UUID column, and in which database? I want to make sure we cover it in our tests. (e.g. varchar(36) at postgresql)

varbinary postgresql

**Comment by MattDelac** [comment]
> @MattDelac Just to make sure I understand, a GUID that in mysql will be stored as `7e4ca296-f7ba-11ec-a5d9-000000000030`, will be stored in postgres as `01111110010011001010001010010110111101111011101000010001111011001010010111011001000000000000000000000000000000000000000000110000`? (i.e. with the dashes removed, as 128-bit)

Actually it looks like for Postgresql, we use varchar(36) (eg `0005e343-55ee-4559-94d2-17c37bcc88f0`)

**Comment by erezsh** [comment]
@MattDelac Can you please install the latest `master` and see if it works now?

You can use 
```
pip install git+https://github.com/datafold/data-diff.git
```

**Comment by MattDelac** [comment]
> @MattDelac Can you please install the latest `master` and see if it works now?
> 
> You can use
> 
> ```
> pip install git+https://github.com/datafold/data-diff.git
> ```

Thanks for the hard work. Really appreciate 😍 

I still get the same error though ... 🤔 
![image](https://user-images.githubusercontent.com/18557047/176499684-3713573b-5141-4d5c-ab5d-03f0081bff1f.png)

**Comment by leoebfolsom** [comment]
@erezsh we are using UUID values generated by an upstream postgres application: https://www.postgresql.org/docs/current/functions-uuid.html

I don't know all the details, but does that link give you adequate detail for testing?

**Comment by erezsh** [comment]
@joeltone The latest `master` should work for your use-case. But looks like there are still edge cases that I need to solve.

**Comment by erezsh** [comment]
@MattDelac I think I fixed it. Can you please try again?

Uninstall, then install from the `fix_uuids` branch -

```
pip install git+https://github.com/datafold/data-diff.git@fix_uuids
```

**Comment by MattDelac** [comment]
> @MattDelac I think I fixed it. Can you please try again?
> 
> Uninstall, then install from the `fix_uuids` branch -
> 
> ```
> pip install git+https://github.com/datafold/data-diff.git@fix_uuids
> ```

Getting this new error

```sh
Traceback (most recent call last):
  File "/Users/mattdelacour/Documents/src/coinlist/pipo/.venv/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/Users/mattdelacour/Documents/src/coinlist/pipo/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mattdelacour/Documents/src/coinlist/pipo/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mattdelacour/Documents/src/coinlist/pipo/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mattdelacour/Documents/src/coinlist/pipo/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mattdelacour/Documents/src/coinlist/pipo/.venv/lib/python3.10/site-packages/data_diff/__main__.py", line 141, in main
    diff_iter = differ.diff_tables(table1, table2)
  File "/Users/mattdelacour/Documents/src/coinlist/pipo/.venv/lib/python3.10/site-packages/data_diff/diff_tables.py", line 304, in diff_tables
    min_key = min(map(key_type.python_type, mins))
  File "/Users/mattdelacour/.pyenv/versions/3.10.3/lib/python3.10/uuid.py", line 174, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by erezsh** [comment]
Hi @MattDelac , I think you're still using an old version, before the latest fix.

I already released these changes. Can you you `pip install data-diff`, make sure it's v0.2.2, and then try?

**Comment by MattDelac** [comment]
> Hi @MattDelac , I think you're still using an old version, before the latest fix.
> 
> I already released these changes. Can you `pip install data-diff`, make sure it's v0.2.2, and then try?

Right sorry.

Looks like it's working 🎉 
![image](https://user-images.githubusercontent.com/18557047/176704976-d8860658-7b6a-4927-ab40-a6afae0450bc.png)

**Comment by erezsh** [comment]
@joeltone Give 0.2.2 a try too!

**Comment by MattDelac** [comment]
@erezsh It might be unrelated, but it found differences between rows even though there are exactly the same when I compare them manually ... 

How could I investigate that ?

**Comment by erezsh** [comment]
@MattDelac I think it's best to open a new issue for that. Provide the type of the columns you're comparing and their values, and then data-diff's output. We'll take it from there.

**Comment by leoebfolsom** [comment]
@erezsh will try when I return to work on Thurs, thanks so much!

**Comment by erezsh** [comment]
We should have support for string columns as primary ids in Presto. If something isn't working, please attached the error message, along with the command you used.

**Comment by akulgoel96** [comment]
@erezsh command that I ran:
`data-diff presto://<user>@<presto-endpoint>:8080/hive/<schema_name> <source_table_name> presto://<user>@<presto-endpoint>:8080/hive/<schema_name> <source_table_name>:8080/hive/<schema_name> <dest_table_name> -k id`

error stack:
`[Presto] Column 'id' of type 'Text()' has no compatibility handling. If encoding/formatting differs between databases, it may result in false positives.
[Presto] Column 'id' of type 'Text()' has no compatibility handling. If encoding/formatting differs between databases, it may result in false positives.
Traceback (most recent call last):
  File "/home/astro/.local/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/astro/.local/lib/python3.9/site-packages/data_diff/__main__.py", line 87, in main
    return _main(**kw)
  File "/home/astro/.local/lib/python3.9/site-packages/data_diff/__main__.py", line 184, in _main
    diff_iter = differ.diff_tables(table1_seg, table2_seg)
  File "/home/astro/.local/lib/python3.9/site-packages/data_diff/diff_tables.py", line 324, in diff_tables
    raise NotImplementedError(f"Cannot use column of type {key_type} as a key")
NotImplementedError: Cannot use column of type Text() as a key`

Using the latest version (v0.2.3)

**Comment by erezsh** [comment]
@akulgoel96 Currently data-diff only supports UUID string columns, and looks like it couldn't find UUID values. Can you provide here a few sample values from the id column?

**Comment by akulgoel96** [comment]
@erezsh yes, these are not UUID columns but just a standard unique alphanumeric string values. Some sample values: 
```IbofYylUPuqDH8
J5tTQIAQekIqOW
IbpIqpXYgvnudU
IbpMPU0jkSdhnL
IbtsfxsFzJ38oH
IbtqLddm9nNVTh
IbvUo0LjCvSfbc
IbxziIuBJDkkJu
J5tjRn0vDXP3s5
J5u3TiMLfvSHFG

**Comment by leoebfolsom** [comment]
Just reporting back that the tool is now accepting our UUID values as primary key. Thanks!

**Comment by akulgoel96** [comment]
@erezsh just checking in, do you have maybe some workaround in mind that we can use here? This is the only hindrance that we are facing currently to onboard this tool in our ecosystem

**Comment by erezsh** [comment]
@akulgoel96 I'll try to have a PR ready this week that would support it.

**Comment by erezsh** [comment]
@akulgoel96 Can you please check if PR #179 solves this?

You can use this:
```
pip install git+https://github.com/datafold/data-diff.git@alphanum_ids
```

**Comment by akulgoel96** [comment]
Hey @erezsh, this is working perfectly fine, thank you! I am just facing some performance issues since the alpha numeric ID's are random and have big gaps b/w them, so currently looking into tweaking the bisection factor and bisection threshold values. If I face issues, I'll open up a new issue as mentioned in README.

Thanks again for pushing out this change so quickly!

**Comment by erezsh** [comment]
@akulgoel96 Happy to hear it! Big gaps shouldn't cause any performance issues, but an uneven distribution of the keys might.

If playing around with the options doesn't help, let us know. We have a few tricks we can try to solve it.

**Comment by erezsh** [comment]
Fixed.
