### ISSUE TITLE
contributors are erased from commit

### ISSUE THREAD

**Issue by qsliu2017** [datafold/data-diff#591]
the contributor image in readme does NOT show all community contributors since PR author is erased from commit in the main branch. I believe it's a GitHub PR merge issue.  Please consider `squash and merge`  or `rebase and merge`.

ref: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges

**Comment by dlawin** [comment]
Hey @qsliu2017, I think the commit may have been from a different email address than your github account? 

<img width="698" alt="Screenshot 2023-05-23 at 9 01 18 PM" src="https://github.com/datafold/data-diff/assets/11282254/7160588c-bfd9-40a7-b6f2-abd8ed82508b">

Seems like you can associate the commit by linking your email to the github account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

**Comment by dlawin** [comment]
https://github.com/datafold/data-diff/commit/80fb09b2dc61c2bb211ab50e1819878863d17998

**Comment by qsliu2017** [comment]
hi @dlawin, I don't think it's the cause. see 7ee154b, I am neither the author nor the committer.

![image](https://github.com/datafold/data-diff/assets/57934883/e46bb777-4ea2-4118-ae0b-811972e45498)

**Comment by qsliu2017** [comment]
FYI, 77ece21387319e11b2c5d3de39828bfdcbc501aa also triggers this issue

**Comment by dlawin** [comment]
> FYI, [77ece21](https://github.com/datafold/data-diff/commit/77ece21387319e11b2c5d3de39828bfdcbc501aa) also triggers this issue

You can see that Leo has a contribution for the parent commit here: https://github.com/datafold/data-diff/commits?author=leoebfolsom

There needs to be a link between the github account and commit email. For example you are not receiving contributions from your own repo here:
<img width="560" alt="Screenshot 2023-05-23 at 10 36 11 PM" src="https://github.com/datafold/data-diff/assets/11282254/f258b056-123b-4716-8e35-bf56e9e0fb32">
<img width="1254" alt="Screenshot 2023-05-23 at 10 37 47 PM" src="https://github.com/datafold/data-diff/assets/11282254/04df6c73-a61b-4ded-b0cc-af23aceb1056">

**Comment by kylemcnair** [comment]
more context highlighting Leo still being tagged to the commit (I had started typing this before Dan commented, gonna send it anyway in case it helps)

<img width="954" alt="Screen Shot 2023-05-23 at 9 35 34 PM" src="https://github.com/datafold/data-diff/assets/40182913/5e11ee6b-211c-4b89-a9d3-2ac5e08154f9">

<img width="928" alt="Screen Shot 2023-05-23 at 9 35 58 PM" src="https://github.com/datafold/data-diff/assets/40182913/f37cbcd8-1d44-4f64-a41e-759b62ecbd6e">

<img width="948" alt="Screen Shot 2023-05-23 at 9 36 42 PM" src="https://github.com/datafold/data-diff/assets/40182913/61a8fc55-250a-44eb-970c-fb49e1b9bb11">


VS 

No link to a GitHub user 
https://github.com/datafold/data-diff/pull/548/commits/80fb09b2dc61c2bb211ab50e1819878863d17998

<img width="1227" alt="Screen Shot 2023-05-23 at 9 42 51 PM" src="https://github.com/datafold/data-diff/assets/40182913/deaf6379-a8df-4a98-b240-cb0b9e855070">

**Comment by qsliu2017** [comment]
@dlawin @kylemcnair Thank you so much for clarifying! I've linked that email address to my account. however I'm still not in the contributor list. maybe that commit is not in master branch.

> If all your commits in the repository are on non-default branches, you won't be in the contributors graph.

ref: https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors#troubleshooting-contributors

**Comment by dlawin** [comment]
Looks like it's showing up now! It must take a bit to propagate
