### ISSUE TITLE
Add support for BigQuery service accounts

### ISSUE THREAD

**Issue by williebsweet** [datafold/data-diff#595]
**Is your feature request related to a problem? Please describe.**
I'd like to use the data-diff with a BigQuery service account. The current implementation only allows for [auth through `gcloud auth application-default login`](https://github.com/datafold/data-diff/blob/c152ae2cae79f84f7d21c95fb4a7e65f647ad7b4/data_diff/dbt_parser.py#L269). Using a BigQuery Service account requires auth via `gcloud auth activate-service-account`.

**Describe the solution you'd like**
A connection that supports `gcloud auth activate-service-account`

**Comment by dlawin** [comment]
Hey @williebsweet, are you using the "service account file" described here? https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-file

Or something else?

**Comment by williebsweet** [comment]
> Hey @williebsweet, are you using the "service account file" described here? https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-file

Yes, I am.

**Comment by dlawin** [comment]
Hey @williebsweet this is available in 0.7.9, lmk if you run into any issues

**Comment by williebsweet** [comment]
Thanks @dlawin!
