### ISSUE TITLE
Limit and/or sort columns by # of diffs

### ISSUE THREAD

**Issue by kylemcnair** [datafold/data-diff#597]
**Is your feature request related to a problem? Please describe.**
[Customer feedback](https://datafold.slack.com/archives/C02D6KUSGF8/p1685125104799099?thread_ts=1685123615.501399&cid=C02D6KUSGF8)
> I use data diff sometimes during development on single ad-hoc queries to see if there any impact before pushing it into a dbt build. Sometimes one can get noisy columns with small differences, so would be great to be able to filter on this, like for example, sort by the largest difference in a particular column

**Describe the solution you'd like**
This is sort of two feature requests - can break this up as needed.

1) a solution where you can pass columns to include or exclude, and _only_ diff those columns
2) a solution where you can sort the diffed columns by # of diffs
2b) perhaps a flag to only display columns with x # of diffs. Something like `--min-diffs 10`

**Describe alternatives you've considered**

**Additional context**

**Comment by dlawin** [comment]
1a is supported via the include/exclude configs here: https://docs.datafold.com/guides/dbt_advanced_configs#include--exclude-columns

I think to keep the scope on this small we should focus on 2a and later decide if we want to iterate on 2b or similar
