### ISSUE TITLE
PK inference not working in scenario

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#598]
**Describe the bug**
PK inference doesn't work when my model config looks like 

```
version: 2

models:
  - name: model_name

    columns:
      - name: sk
        description: '{{ doc("sk") }}'
        test:
          - not_null
          - unique
```

**Comment by jakeberesford-palmetto** [comment]
To clarify, this conifg does work because of the `meta`. However, it should work without it since the column is tested for uniqueness.

**Comment by dlawin** [comment]
> To clarify, this conifg does work because of the `meta`. However, it should work without it since the column is tested for uniqueness.

Hey @jakeberesford-palmetto  I’ve been unable to reproduce this with a similar config so it seems there's something more nuanced going on:
```
  - name: simple_example
    columns:
      - name: id
        description: '{{ doc("id") }}'
        tests:
          - not_null
          - unique
```

Are you still able to as well? What dbt version are you on?

One thing that would help is the message you see here at the end for that model:
```
➜  dbt-beers git:(master) ✗ dbt -v                                                           
Core:
  - installed: 1.5.0

➜  dbt-beers git:(master) ✗ data-diff --dbt --select simple_example --debug                  
Running with data-diff=0.7.8
[11:32:15] INFO - Parsing file dbt_project.yml
[11:32:15] INFO - Parsing file target/manifest.json
[11:32:16] INFO - Parsing file /Users/dan/.dbt/profiles.yml
[11:32:16] DEBUG - Found PKs via Uniqueness tests: {'id'}
```

You aren't seeing any warning/error messages? Something like: `Failure while finding unique cols:` ?
