### ISSUE TITLE
TypeError while running data-diff between MySQL and Snowflake via python api

### ISSUE THREAD

**Issue by srik1981** [datafold/data-diff#606]
**Describe the bug**
Trying to run data-diff with min_key=[0] and max_key=[10000] via python, running into the following exception - 

**`<[TableSegment] Attribute 'min_key' expected value of type (NoneType+Vector). Instead got [0]>`**

code block within python file with the error - 
       `for row in data_diff.diff_tables(source_con, target_con, bisection_factor=100, min_key=[0], max_key=[10000]):`

Exception - 
```
        <[TableSegment] Attribute 'min_key' expected value of type (NoneType+Vector). Instead got [0]>
        <class 'TypeError'>
```

**Describe the environment**

Python 3.9.12
data-diff==0.7.8
mysql-connector-python==8.0.29

This was run on Mac with the Apple M1 Pro Chip running macOS Ventura 13.4.

**Comment by dlawin** [comment]
Hi @srik1981 thanks for reporting this, what was the column type of the key column?

**Comment by dlawin** [comment]
relates to https://github.com/datafold/data-diff/issues/603

**Comment by leoebfolsom** [comment]
Hi @srik1981, any chance you could share the column type of the key column?

**Comment by srik1981** [comment]
> Hi @srik1981, any chance you could share the column type of the key column?

`Integer` I believe

**Comment by glebmezh** [comment]
Hi @srik1981,

I'm sorry for the delay in following up on this. Thank you for taking the time to raise this issue!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support. 

If that's of interest, over the past few months, we have rewritten the diffing engine in Datafold Cloud and solved many issues that existed in this package's diffing algorithm. 

-Gleb
