### ISSUE TITLE
Optionally structure summary output as machine-readable (e.g., JSON)

### ISSUE THREAD

**Issue by leoebfolsom** [datafold/data-diff#607]
**Is your feature request related to a problem? Please describe.**
The CLI output is not structured for machine readability.

**Describe the solution you'd like**
Feedback received from a beta user:

> I was thinking as the high level summary stat from the regular data-diff run but in JSON format.
> The idea being to be able to implement automatic checks in a CI/CD type of environment... Something like if diff(criteria) > threshold then alert a human (on slack 🤷‍♂️) for manual review...
> I could definitely see something like that working pretty nicely in a deployment workflow 👍

**Describe alternatives you've considered**
The current tuple format of the core data-diff (non-`--dbt`) output is machine readable, so that could be adapted. OCR could also be used on a screenshot of the current output 🙃 🚫

**Comment by dlawin** [comment]
@leoebfolsom `--dbt --json` is available now
