### ISSUE TITLE
What is data-diff? And where is all the documentation?

### ISSUE THREAD

**Issue by erezsh** [datafold/data-diff#608]
1. What is data-diff?

According to the current readme,

> data-diff is an open source package that you can use to see the impact of your dbt code changes on your dbt models as you code.

Is that true? I'm pretty sure data-diff has always been something else. For example, here is a HN post explaining what is data-diff, that doesn't even contain the word dbt: https://news.ycombinator.com/item?id=31837307

Perhaps you're thinking of some imaginary package called dbt-data-diff?

The readme doesn't address this discrepancy at all.

2. Where is all the documentation?

The developers of data-diff had put a lot of effort into writing detailed documentation that explains how data-diff works, that provides all kinds of technical context, and helps new developers contribute. What happened to all that documentation, where did it go?

It used to be in datafold.com, but it is no longer there.

**Comment by dlawin** [comment]
@erezsh thanks for opening this. I'm going to let @glebmezh weigh in

**Comment by erezsh** [comment]
@dlawin Any idea if and when he's going to respond?

**Comment by moulay-datacore** [comment]
I was wondering where all the documentation went, is this becoming a dbt centric tool ?

**Comment by koenvb** [comment]
looks like indeed. I was also using it as a data diffing tool but seems now you have to use DBT or so?

**Comment by dlawin** [comment]
Non-dbt doc is here:
https://docs.datafold.com/reference/open_source/cli
https://data-diff.readthedocs.io/en/latest/python-api.html
https://github.com/datafold/data-diff/blob/master/docs/technical-explanation.md

**Comment by glebmezh** [comment]
Thanks @erezsh for raising this – we reworked the README to cover the broader spectrum of use cases with links to further materials and docs.
