### ISSUE TITLE
dbt only?

### ISSUE THREAD

**Issue by danthelion** [datafold/data-diff#610]
Did the project pivot to dbt-only? I have a use-case that would require the Python API but I can't seem to find any reference to it anymore?

**Comment by dlawin** [comment]
Hey @danthelion, dbt has been a focus for us as of late but the previous use cases are still supported. 

Here is the documentation for non-dbt CLI: https://docs.datafold.com/reference/open_source/cli/

And the python API: https://data-diff.readthedocs.io/en/latest/python-api.html

**Comment by dlawin** [comment]
> Thanks @dlawin, are these use cases planned to be supported in the future as well?

Yes. **_Expanding_** on those existing features I'd say is less likely to be done by we maintainers in the near future. But we'd happily accept community contributions

**Comment by dlawin** [comment]
Hey @danthelion I'm going to close this but feel free to reopen
