### ISSUE TITLE
Using the same input to compare a model change

### ISSUE THREAD

**Issue by rodrigo-fss** [datafold/data-diff#615]
**Is your feature request related to a problem? Please describe.**

When working on a dbt model change, I'd love to see how the new model output data compare to the output of the production model version **given the same input data**.  

Today the local model reads and writes to dev and gets compared to the prod table, run with prod data.

**Describe the solution you'd like**

For the proper comparison to run today, I'd have to sync my dev and prod databases before running data-diff, which adds an extra layer of complexity I was hoping I didn't have to deal with.

I didn't find anything related in the docs, but is there a way to make data-diff read data from prod and write to dev? This would be the most reliable way to diff a model change.

**Comment by dlawin** [comment]
@rodrigo-fss At this time I think this falls outside the scope of data-diff

One option I'd recommend is to utilize the --state and --defer flags in dbt, this allows you to essentially point local models to "prod" data
