### ISSUE TITLE
data diff hot reloading

### ISSUE THREAD

**Issue by sungchun12** [datafold/data-diff#621]
**Is your feature request related to a problem? Please describe.**
It can get tedious writing out the full command because I make slight changes to the dbt command and it slows down my pace. Arrow-keying up for command history isn't enough.
`dbt run --select <MODEL> && data-diff --dbt`

**Describe the solution you'd like**

I invoke `dbt run --select <MODEL>` and `data-diff` gets invoked automatically without ever having to write out or manually invoke the command. 

- It can run as a background process to notice changes to the `run_results.json` and `manifest.json` files to then run the diffs
- A clever mechanism that when the compiled files are created it pokes at the data-diff process to be invoked vs. a background process polling for changes
- Python packages that come to mind: `watchdog`

**Describe alternatives you've considered**
- Build my own alias command, but then I'd have to maintain it and I'm not a fan of that

**Additional context**

I want it to look and feel like the terminal experience here: https://www.loom.com/share/ecfbdfb981e4443d94d2c95f16176118?sid=65968680-12ea-45bb-bd95-be43b19941c5

**Comment by sungchun12** [comment]
Happy to build this feature out myself if capacity is an issue!

**Comment by dlawin** [comment]
> I invoke dbt run --select <MODEL> and data-diff gets invoked automatically without ever having to write out or manually invoke the command.

This would be awesome. In an ideal state data-diff is not adding any additional process to the development workflow, we're removing repetitive process and tedious commands.

**Comment by sungchun12** [comment]
Let's close this out because the VS Code extension has this built-in
