### ISSUE TITLE
Support quoted identifier dbt_project.yml config

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#640]
Parse the setting here and utilize it when constructing comparison paths:
https://docs.getdbt.com/reference/project-configs/quoting

If I set that to true and use lowercase table names with Snowflake for example, none of my tables are diffed appropriately.

**Comment by michelr** [comment]
I have the same problem. From debug:
```DEBUG    Running SQL (Snowflake): ALTER SESSION SET TIMEZONE = 'UTC'                                       base.py:354
15:47:56 DEBUG    Running SQL (Snowflake): SELECT column_name, data_type, datetime_precision, numeric_precision,    base.py:354
                  numeric_scale FROM DATABASE.information_schema.columns WHERE table_name = 'DIMCARD' AND
                  table_schema = 'DBT'
15:47:57 DEBUG    Snowflake: Table 'DATABASE.DBT.DIMCARD' does not exist, or has no columns
```


We use quotations for table names and the table is called "DimUser"

**Comment by glebmezh** [comment]
Hi @dlawin and @michelr,

I'm sorry for the delay in following up on this. Thank you for taking the time to raise this issue!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support. 

If that's of any help, quoted table names are supported when diffing in Datafold Cloud.

-Gleb
