### ISSUE TITLE
Get prod alias from `--state` manifest file when provided

### ISSUE THREAD

**Issue by sebaap** [datafold/data-diff#646]
**Is your feature request related to a problem? Please describe.**
We have an uncommon BigQuery setup where our prod environment consist of multiple GCP projects, but dev is a single project. In this setup the name of the underneath tables for each model is different between the two environments, so currently data-diff doesn't work for us because it tries to use the same model alias in both environments.

**Describe the solution you'd like**
When providing a prod manifest via the `--state`, take the alias for prod from the manifest instead of using the same one from the `run_results` file. This should be fairly easy to implement and would allow us to use data-diff :)

**Describe alternatives you've considered**
With my very limited familiarity with the code, I don't see any other alternative to be honest.
Migrating to a single project setup is not an option for us as it would require a huge effort.

**Additional context**
I'm happy to submit a PR if help is needed, as I have a working version of this already.

**Comment by dlawin** [comment]
I think this was overlooked, no reason not to use the prod alias when we have the manifest here https://github.com/datafold/data-diff/blob/eb22d3e9a8b1a098f113c7a37dec9a8efb25c025/data_diff/dbt.py#L171

**Comment by dlawin** [comment]
> I'm happy to submit a PR if help is needed, as I have a working version of this already.

Please do and don't worry about the tests if some break, happy to take it the last mile
