### ISSUE TITLE
Add a progress bar for each data diff

### ISSUE THREAD

**Issue by sungchun12** [datafold/data-diff#672]
**Is your feature request related to a problem? Please describe.**

I want a beautiful progress bar for my data diffs so I have predictability in my workflow. There are times where I wonder if a data diff will take 10 seconds or 1 hour. Even a simple rule of thumb estimate is better than nothing.

This is not meant to be a "cute cosmetic" but serves to cue when I should stay and watch my terminal or leave to play with my dog while a data diff is running long. Think: save precious time and cue context switching when that's more productive.

**Describe the solution you'd like**
![alive-demo](https://github.com/datafold/data-diff/assets/19176976/0890f436-9941-4784-bc06-79fe12c534c8)
https://github.com/rsalmei/alive-progress This is a fantastic role model!

During each diff, it shows a progress bar to indicate how long it's taking and estimated completion time in seconds/hours

Research: 
https://builtin.com/software-engineering-perspectives/python-progress-bar
https://github.com/tqdm/tqdm

**Describe alternatives you've considered**

**Additional context**

**Comment by sungchun12** [comment]
I will make this happen, maybe not as a progress bar but at least a running seconds counter. The main thing is to build predicability for data-diff users.

**Comment by glebmezh** [comment]
That's a cool idea @sungchun12!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support.

-Gleb
