### ISSUE TITLE
Allow joindiff between snowflake databases at same URI connection string

### ISSUE THREAD

**Issue by leoebfolsom** [datafold/data-diff#674]
**Is your feature request related to a problem? Please describe.**
I want to be able to use joindiff in all cases when I am diffing within a database. `data-diff` thinks I'm diffing cross-database when I try to compare tables between two Snowflake "databases" which exist in the same URI connection string.

Using joindiff would be a useful workaround given some of the current limitations of hashdiff, specifically https://github.com/datafold/data-diff/issues/539

**Describe the solution you'd like**
Adjust [this logic](https://github.com/datafold/data-diff/blob/2697d3aa696c3fcb01f8820332924e189661c69f/data_diff/joindiff_tables.py#L149) so it doesn't naively interpret the Snowflake "database" as an actual database that requires true cross-database diffing. Instead, interpret the URI connection strings that are entered and consider them to be "in-db" as long as the Snowflake account string matches between the two tables.

**Describe alternatives you've considered**
- clumsy/hacky workarounds
- wait until texts-based PKs are supported in hashdiff

**Comment by leoebfolsom** [comment]
Not sure if this is a bug -- added the label but feel free to remove

**Comment by dlawin** [comment]
Maybe what we need to do is clarify that `<table_a> <table_b>` actually mean <qualified_paths_that_overides_db_defaults>

**Comment by leoebfolsom** [comment]
@dlawin you're right -- I'm going to open a separate issue that proposes an improvement to the CLI UX

**Comment by leoebfolsom** [comment]
@dlawin before I do that, I'm going to take a stab at improving our docs to make some of the current state more clear
