### ISSUE TITLE
--stats gives weird info message

### ISSUE THREAD

**Issue by kning** [datafold/data-diff#68]
I get the message 
`Diff-Total: 3 changed rows out of None`

Looking at the code, it looks like None should be the count of records in table 1. My test case is a really small table (only 3 rows) so wondering if that's what's throwing things off.
![image](https://user-images.githubusercontent.com/1820651/174196842-00aa2b85-8d1f-4ba7-a54a-07f1f299f84b.png)

**Comment by sirupsen** [comment]
This happens when all the rows were downloaded, not checksummed. Will fix

**Comment by erezsh** [comment]
I believe @sirupsen fixed this.
