### ISSUE TITLE
Support all dbt connection attributes aliases

### ISSUE THREAD

**Issue by sar009** [datafold/data-diff#689]
**Is your feature request related to a problem? Please describe.**
Not all dbt connection aliases are supported

**Describe the solution you'd like**
Implement all dbt connection aliases

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sar009** [comment]
adding fix in https://github.com/datafold/data-diff/pull/690

**Comment by dlawin** [comment]
Resolved in #690 

@sar009 ty for the contibution!
