### ISSUE TITLE
Is it possible to support schema-less non-SQL DBs like Neo4J graphDB?

### ISSUE THREAD

**Issue by Veilkrand** [datafold/data-diff#692]

**Comment by sungchun12** [comment]
Do you have example source to target data-diff examples you wish were possible today? 

What's an example of the graph payload and how you'd like that to diff against something like snowflake?

**Comment by Veilkrand** [comment]
For example I have one source in MySQL and the other is Neo4J. I want to validate Order.delivered between both sources for the last day as interval.

SQL for MySQL:
```
SELECT o.delivered FROM order o WHERE last_updated> NOW() - INTERVAL 1 DAY
```

Cypher for Neo4J:
```
MATCH (o:Order) WHERE o.updated > datetime() - duration('P1D') RETURN o.delivered
```

Neo4J Order object is schema-less, and it would need a transform for casting to be compared to the MySQL column.

**Comment by sungchun12** [comment]
Thanks that's a great example. Does Neo4J data flow into MySQL or the other way around?

**Comment by Veilkrand** [comment]
MySQL should be the source of truth in this case

**Comment by sungchun12** [comment]
Thanks I'll talk internally with my team about this!

**Comment by sungchun12** [comment]
@Veilkrand We don't plan to support graph databases on our roadmap. `data-diff` is primarily focused on migration/replication validation when diffing across two different databases and we're focusing our efforts there before we move onto more unique use cases like this one. 

Thanks for your patience!
