### ISSUE TITLE
Support for dbt_constraints for inferring the PK

### ISSUE THREAD

**Issue by rverheijen** [datafold/data-diff#699]
**Is your feature request related to a problem? Please describe.**
Not (really) a problem, but a wanted enhancement.

**Describe the solution you'd like**
Support for dbt_constraints for inferring primary keys.

**Describe alternatives you've considered**
Defining primary keys twice.

**Additional context**
[Snowflake-Labs/dbt_constraints](https://github.com/Snowflake-Labs/dbt_constraints)

**Comment by chrisboonstra** [comment]
Would be a very nice feature and a time saving feature aswell

**Comment by dlawin** [comment]
Agreed, this would be a nice feature. Any interest in submitting a PR for this?

The PKs are inferred in this method here: https://github.com/datafold/data-diff/blob/master/data_diff/dbt_parser.py#L434

Assuming the constraint is tied to the model's node in manifest.json, should be possible to extend the method with another if statement

e.g.
```python
    from_constraint = [] or None # TODO add column names with PK constraints
    if from_constraint:
        logger.debug("Found PKs via Constraint: " + str(from_constraint))
        return from_constraint
```
