### ISSUE TITLE
Support separate prod profile

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#705]
**Is your feature request related to a problem? Please describe.**
When using `--dbt`, I'd like to be able to specify a profile to use for the prod side of the comparison.

This would allow me to use the feature when my dev and prod environments are on different snowflake accounts for example. The feature currently assumes a single profile can access both dev and prod.

**Comment by sungchun12** [comment]
Would this bring xdb diffs to the dbt workflow?
