### ISSUE TITLE
psycopg2.errors.CannotCoerce: cannot cast type text to bit

### ISSUE THREAD

**Issue by tjlgriffiths** [datafold/data-diff#733]
Our engineers are making changes to the data model so we'd like to use `data-diff` to ensure that the downstream models won't be affected. We're using AWS Redshift with DBT, our project has about 300 models with a `prod`, `dev`, and `sandbox` environment. 

The `dev` and `sandbox` DBs both sit inside a `dev` cluster. We were able to set up `joindiff` tests, comparing 2 models within the same DB using the CLI. However, we've had trouble using `hashdiff` to compare the same model between `dev` and `sandbox`. Unfortunately our node type isn't supported for cross-database queries by AWS, so we're unable to use the DBT functionality for `data-diff`. For that reason, we're using the CLI and giving it two separate connections outside of DBT to compare the same table between `dev` and `sandbox`. However, no matter which model we use for the comparison, we get a `psycopg2.errors.CannotCoerce: cannot cast type text to bit` error, which stops the comparison.

important note: we’re using a ‘redshift://’ connection string, but the tool persists with using the postgres connector. we have tried to override this using datadiff.toml config, but eventually hit the same error and the tool was still using the postgres connector despite us setting driver = "redshift".

**Comment by dlawin** [comment]
Workaround is to revert to `0.8.4`, but we're working on a fix
