### ISSUE TITLE
PostgreSQL and MySQL interpret string ordering differently

### ISSUE THREAD

**Issue by mrn3** [datafold/data-diff#762]
**Describe the bug**
Data diff results are not correct when comparing PostgreSQL and MySQL.  This is because of the difference in the sorting order of hypens.

alphanum is being used to convert a string to number with that alphanum as base, so if we have hyphen - in the alphanum it is used to generate a set of  strings based on range and that range will change across databases as the hyphen is treated differently by the databases.

This is also very related to https://github.com/datafold/data-diff/issues/513 and may be a duplicate.

Make sure to include the following (minus sensitive information):
- This issue is caused when issuing data-diff comparison of a PostgreSQL and MySQL database table.

**Describe the environment**

Debian Linux with data-diff 0.9.7.

**Comment by mrn3** [comment]
I am working on https://github.com/datafold/data-diff/pull/763/files to resolve this issue.

**Comment by mrn3** [comment]
This fixes the issue, but isn't ideal yet because it breaks other cases.  We plan to make it so either a user will choose which kinds of alphanums they want and pass it in as a parameter, or it will automatically detect it based on the type of database.

**Comment by dlawin** [comment]
> Data diff results are not correct when comparing PostgreSQL and MySQL. This is because of the difference in the sorting order of hypens.

@mrn3, I wonder if we canset the collation to something equivalent? 

Only tangentially related, but I was considering setting mysql collation in this PR: https://github.com/datafold/data-diff/pull/712

https://dev.mysql.com/doc/refman/8.0/en/charset-mysql.html

**Comment by mrn3** [comment]
Yeah, we considered that - so you are thinking that maybe just setting the collation will resolve our original issue?

I do know that the fix I have that PR for does fix the issue.

**Comment by glebmezh** [comment]
Hi @mrn3,

I'm sorry for the delay in following up on this. Thank you for opening this issue and looking into the potential solutions!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support. 

Over the past few months, we have completely rewritten the diffing engine in the cloud and have solved the fundamental issues with the original algorithm used in the data-diff package, as well as collation support, etc. Feel free to take it for a trial or contact us at support@datafold.com if you have any questions.

-Gleb
