### ISSUE TITLE
Allow source and target to have different column names

### ISSUE THREAD

**Issue by sirupsen** [datafold/data-diff#79]
You might have a column called `money` in one database, and `amount` in another. Today we don't have a way to have the columns have different names across the two databases. In the Python API, perhaps it's sufficient to just make it based on the position in the column tuple.

For the CLI, maybe we could use: `-c amount:money`.

**Comment by JCZuurmond** [comment]
Hi all, is anyone working on this? I would like to have this feature!

**Comment by erezsh** [comment]
@JCZuurmond Just FYI that this is already possible using the Python API.

As for the CLI, we don't have any decision. But if you vote this issue up, it increases the chances of it getting implemented.

**Comment by JCZuurmond** [comment]
Thanks, I am using the Python API for now. I expect this feature is not needed - at least for now
