### ISSUE TITLE
The primary key is not a number, and is a joint primary key, how should you compare the data?

### ISSUE THREAD

**Issue by acracker** [datafold/data-diff#799]
There is a daily price table of a commodity in each of the two MYSQL, the primary key is id, and the commodity + date is unique in the table. I need to compare whether the price of each commodity in the two databases is the same every day, or whether there is any deficiency. What should I do?

**Comment by sungchun12** [comment]
Can you create a UUID from the two columns so it's alphanumeric? 

```sql
CREATE TABLE YourTable (
    column1 VARCHAR(36) NOT NULL,
    column2 VARCHAR(36) NOT NULL,
    uuid AS (CONCAT(column1, '-', column2)) PERSISTENT PRIMARY KEY
);
```
