### ISSUE TITLE
Snowflake/BigQuery parallelism

### ISSUE THREAD

**Issue by sirupsen** [datafold/data-diff#81]
The drivers don't natively support multi-threading, so we need to create our own thread-pool. This should improve their performance quite a bit, so we can issue multiple checksum queries concurrently.

https://github.com/datafold/data-diff/pull/43#discussion_r884781675

**Comment by erezsh** [comment]
I think we're already doing this? I'm not sure what you're suggesting.

**Comment by sirupsen** [comment]
It was referring to the linked comment you wrote, but maybe I am misunderstanding?

My understanding was that Snowflake and BigQuery's clients don't support thread-pools, so we cannot actually issue multiple queries in parallel. We'd have to thread-pool ourselves?

**Comment by erezsh** [comment]
I'm closing this for now, because it sounds like it was a misunderstanding.
