### ISSUE TITLE
PG connection URL has special characters in password

### ISSUE THREAD

**Issue by idling11** [datafold/data-diff#811]
**Describe the bug**
When connect to PG, if my password has special characters, may be like '@'.  The code goes to dns parser will fail to extract the right password.

**Comment by idling11** [comment]
My advice is： when user construct the url, he can use `urllib.parser.quote` to convert the special characters once. Make sure dns parser can extract right connection params.  Then we use `urllib.parser.unquote` to convert the characters back to the connection dict.

**Comment by idling11** [comment]
I got a pr for this issue.  And fix a mysql reconnection bug by the way. https://github.com/datafold/data-diff/pull/812

**Comment by sungchun12** [comment]
@idling11 Thanks so much for raising this issue! I'll take a deeper look tomorrow into your PR.
