### ISSUE TITLE
Config Files

### ISSUE THREAD

**Issue by sirupsen** [datafold/data-diff#82]
We should likely create a config file format to avoid having to create wrapper-scripts with the right bisection factor, threshold, concurrency, URIs, tables, etc.

**Comment by abhinav1912** [comment]
Using a config to define constants like bisection factor and threshold make sense. What do you mean by _"URIs, tables, etc"_ here?

**Comment by sirupsen** [comment]
@abhinav1912 I was thinking that you'd have the ability to do e.g. `data-diff config.yml`, maybe something like this-ish:

```
---
:tables:
- :bisection_factor: 32
  :bisection_threshold: 100000
  :max_age: 8h
  :columns:
  - amount
  :key_column: id
  :tables:
  - :table: transactions
    :uri: postgres://
  - :table: TRANSACTIONS
    :uri: snowflake://
- :min_age: 1h
  :columns:
  - line_items
  :key_column: id
  :updated_column: updated_at
  :tables:
  - :table: orders
    :uri: mysql://
  - :table: orders
    :uri: presto://
```

**Comment by sirupsen** [comment]
I'm good with TOML, but you don't think we should also allow specifying table configuration too?

**Comment by erezsh** [comment]
Not at all, we should support running from a config file. I'm just saying that unpacking the URI is an important part of it.

**Comment by sirupsen** [comment]
Ahhh yes, I see what you're saying! Completely agree.

**Comment by glebmezh** [comment]
@leoebfolsom we have a dedicated product just for that! It integrates with dbt, Github/Gitlab, CI, and your DWH to provide you with full impact analysis for any change to the dbt code. You can see the video demo here: https://www.datafold.com/

**Comment by leoebfolsom** [comment]
Nice demo! I understand that column-level lineage is part of the paid product, but what about a stupider implementation of "compare all same-named tables" not dependent on lineage? Would you be open to including that in the open source version? I understand if that's not in the road map, just want to get a sense for what might be coming.

**Comment by sirupsen** [comment]
@leoebfolsom I think we should support `--all-mutual-tables` to mirror `--all-mutual-columns`. Those two flags would, together, do what you'd like—yeah?

**Comment by leoebfolsom** [comment]
@sirupsen Yes! Thanks! Let me know if you need contributor time and I'd be happy to help if I can.

**Comment by erezsh** [comment]
Another approach for it would be to support a `-k` switch (like in pytest) to collect all the tables whose names match a certain pattern.

**Comment by glebmezh** [comment]
@leoebfolsom right, but FWIW it's not just about lineage, the SaaS tool also provides you deeper analysis into diff including how the metric distributions are changing as well as a turnkey CI and dbt integration – it's optimized for regression-testing dbt code, whereas the open-source data diff really shines with validating cross-DB data consistency.

Totally support adding both `--all-mutual-tables` and `-k` pattern options to the CLI

**Comment by sirupsen** [comment]
@leoebfolsom we'd love your contribution! I'd suggest starting with `--all-mutual-columns`, as `--all-mutual-tables` will require far more changes (and has the former as a dependency anyway).

The best next step would be for you to dive into the code 🐰 and comment on the issue on the approach you plan to take, to make sure you're not wasting cycles before making it into a PR!

**Comment by leoebfolsom** [comment]
@sirupsen got it! I'll comment on the issue when I get a chance to do dive in 🐰 my availability is a bit dependent on other data testing work priorities.

**Comment by leoebfolsom** [comment]
@sirupsen just as a heads up, I will be OOO until July 7. Sorry I wasn't able to jump on this sooner! ofc if someone else can get around to it, don't wait for me, but I'm happy to take a look when I return.

**Comment by sirupsen** [comment]
@leoebfolsom all good, I suspect no-one will work on it before then, but we'll let you know if so :)

**Comment by sirupsen** [comment]
@erezsh I like the direction! Some comments:

1. I think we should leave room to be able to specify multiple table pairs in the same file. It will be extremely common, likely more common than not, in the long-term to have multiple tables you want to compare (if not entire databases). We don't support it now, but we should in the next few weeks/months. I think multiple files would make that annoying to deal with, because most things will be the same. I'm completely fine if we scope each file to be only one database pair though, even if we have multiple tables!
2. In the case of (1), we should allow specifying different bisection thresholds, factors, threads, and min-age. It'd be nice to be able to specify it at a global scope, and then override it per table pair.
3. As you've already done, I think all names should be the same as for the CLI 👍🏻 
4. What does specifying columns look like? I'm assuming you've left it out because you think it should be specified on the CLI? I think you should be able to configure everything in the config file so you can just run data-diff against it, and boom. In particular, we should make room for the column names being different in source and destination as per https://github.com/datafold/data-diff/issues/79

**Comment by erezsh** [comment]
1. I agree we should take that into account. This example was only for defining databases. We can also have sections of other categories, like `[run.my_run_name]` which will include the names of the tables to diff (toml accepts arrays), and other local settings. I'll update it in my example.
2. See (1)
3. Yep
4. Maybe `source.columns = ["col1", "col2"]` ?

**Comment by erezsh** [comment]
Updated proposal (example with several variations) :

```python
[database.test_postgresql]
driver = "postgresql"
user = "postgres"
password = "Password1"

[database.test_presto]
driver = "presto"
user = "presto"
host = "127.0.0.1"
catalog = "postgresql"
schema = "public"

[run.default]
update_column = "timestamp"
verbose = true

[run.pg_presto]
1.database = "test_postgresql"
1.table = "rating"
2.database = "test_presto"
2.table = "rating_del1"

[run.pg_pg]
1.database = "test_postgresql"
1.table = "rating"
2.database = "postgresql://postgres:Password1@/"
2.table = "rating_del1"

[run.pg_pg_threaded]
threads = 4     # cpu threads
1.database = "test_postgresql"
1.table = "rating"
1.threads = 4
2.database = "test_postgresql"
2.table = "rating_del1"
2.threads = 2
```

**Comment by erezsh** [comment]
I consider this closed, but feel free to continue the discussion.
