### ISSUE TITLE
`pg_get_cols` query for Redshift is erroring out

### ISSUE THREAD

**Issue by mjkanji** [datafold/data-diff#875]
**Describe the bug**
I'm trying to diff two views in Redshift. However, when I run `data-diff` using either `--dbt` or the fully qualified URLs, I'm getting the following error:

```bash
psycopg2.errors.DatatypeMismatch: query-specified return row and actual function return row do not match
```

Having run each of the queries shown in `--interactive` mode, I was able to narrow it down to the following query:

```sql
select * from pg_get_cols('my_schema.my_view')
cols(col_name name, col_type varchar)
```

Looking at the [Redhisft docs on `pg_get_cols`](https://docs.aws.amazon.com/redshift/latest/dg/PG_GET_COLS.html), it seems the right way to run this query is as follows:

```sql
select
    * -- or col_name, col_type if you're only interested in those columns  
from pg_get_cols('my_schema.my_view')
cols(view_schema name, view_name name, col_name name, col_type varchar, col_num int)
```

This query does work.

(Also, as a side note, when I use `--interactive`, it does turn on debugging logs, but the queries are all run without asking me to interactively confirm the query.)

If possible, please paste these as text, and not a screenshot.

**Describe the environment**

I'm on Linux (WSL2 on Windows) and data-diff v0.11.1.

**Comment by glebmezh** [comment]
Hi @mjkanji,

Thank you for trying out data-diff and for taking the time to open this issue. We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support. Diffing functionality will continue to be available in Datafold Cloud. Feel free to take it for a trial or contact us at support@datafold.com if you have any questions.

-Gleb
