### ISSUE TITLE
use pymssql  replace pyodbc to connect mssql in aws glue

### ISSUE THREAD

**Issue by MengruXiao** [datafold/data-diff#878]
**Describe the bug**
when i use datadiff in aws glue python shell,i can not connect mssql because pyodbc need odbc driver: ODBC Driver 18 for SQL Server ,
but aws glue do not support odbc driver,i hope datadiff can use pymssql to connect mssql .
since pymssql is easier for users to install, can it be turned into a configuration port option?

Make sure to include the following (minus sensitive information):

my scripts:

'''
from data_diff import connect_to_table, diff_tables, disable_tracking

mssql_table1 = connect_to_table(mssql, "table", "id") # mssql is a Connection string
redshift_table2 = connect_to_table(redshift, "table", "id")# redshift is a Connection string

for different_row in diff_tables(mssql_table1, redshift_table2):
    plus_or_minus, columns = different_row
    print(plus_or_minus, columns)

'''

Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 18 for SQL Server' : file not found (0) (SQLDriverConnect)")

**Describe the environment**

python 3.9
glue 3.0
datadiff v0.11.1

**Comment by glebmezh** [comment]
Hi @MengruXiao,

Thank you for trying out data-diff and for taking the time to open this issue. We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support. Diffing functionality will continue to be available in Datafold Cloud. We have completely rewritten the diffing engine in the cloud over the past few months and have solved the fundamental issues with the original algorithm used in the data-diff package, as well as a better experience for MS SQL Server 2019+. Feel free to take it for a trial or contact us at support@datafold.com if you have any questions.

-Gleb
