### ISSUE TITLE
Limited support of duckdb dbt adapter credentials

### ISSUE THREAD

**Issue by sergun** [datafold/data-diff#881]
As I see here:
https://github.com/datafold/data-diff/blob/master/data_diff/dbt_parser.py#L388-L392

dbt config parser implemented in data-diff does not cover configuration options of modern duckdb dbt adapter.
E.g. extensions and any s3 related settings are useful:
https://github.com/duckdb/dbt-duckdb?tab=readme-ov-file#duckdb-extensions-settings-and-filesystems

**Comment by sergun** [comment]
[datadiff.PATCH](https://github.com/datafold/data-diff/files/14920373/datadiff.PATCH)
Hi!
Attached find quick patch to parse settings and extension sections from duckdb dbt config.

**Comment by glebmezh** [comment]
Hi @sergun,

Thank you for trying out data-diff, for opening this issue, and even proposing a patch!

We [made a hard decision](https://www.datafold.com/blog/sunsetting-open-source-data-diff) to sunset the data-diff package and won't provide further development or support. Diffing functionality will continue to be available in Datafold Cloud. At the moment, support for DuckDB is on the roadmap for the cloud. Please feel free to contact us at support@datafold.com if you have any questions.

-Gleb
